# 1 Assignment 3

In [1]:
import os
import os
import pickle
import pandas as pd
import numpy as np
import urllib.request

1. Import the `REC0111.sav`, `RE223132.sav` and `RE516171.sav` files and their variables and values labels from this path `"../../_data/endes/2019"`. The name of imported files should be named as `rec_1`, `rec_2` and `rec_3` for files `REC0111.sav`, `RE223132.sav` and `RE516171.sav` respectively. The name of the variable and value labels should be `var_labels1` and `value_labels1` for `rec1`, `var_labels2` and `value_labels2` for `rec2`, and `var_labels3` and `value_labels3` for `rec3`. **Hint: See the section 3.3.4 of [the lecture 3](https://github.com/alexanderquispe/Diplomado_PUCP/blob/main/Lecture_3/Lecture_3.ipynb)**

2. Select the following columns for each data set:
|Data|Columns|
|---|---|
|rec1| CASEID, V000, V001, V002, V003, V004, V007, V008, V009, V010, V011, V012, V024, V102, V120, V121, V122, V123, V124, V125, V127, V133 |
|rec2| CASEID, V201, V218, V301, V302, V323, V323A, V325A, V326, V327, V337, V359, V360, V361, V362, V363, V364, V367, V372, V372A, V375A, V376, V376A, V379, V380 |
|rec3| CASEID, V501, V502, V503, V504, V505, V506, V507, V508, V509, V510, V511, V512, V513, V525, V613, V714, V715 |


Additioanlly, you should update the variables and value labels objects. They must have information only for the selected columns. The new dataframes should be name as `rec1_1`, `rec2_1`, and `rec3_1`. The new varible labels objects should be named as `new_var_labels1`, `new_var_labels2`, and `new_var_labels3`. The new value labels objects should be named as `new_value_labels1`, `new_value_labels2`, and `new_value_labels3` **Hint: Use the `loc` and column names to filter. Update the dictionary.**

3. Generate a new column for `rec1_1` named as `year`. It should be equal to `2019`. Also, you must update this new variable for the `var_labels` dictionary. Generate a new key for `new_var_labels1` and the value for this key should be **"Year of the survey"** **Hint: Use `loc` and `update` method.**

4. Merge `rec1_1`, `rec2_1`, and `rec3_1` using **CASEID**. Name this new object as `endes_2019`. **Hint: Use [this link](https://stackoverflow.com/questions/53645882/pandas-merging-101)**

5. Unify all the `new_var_labels` in one object and `new_value_labels` in another one object. Name these two objects as `var_labels` and `value_labels`. Use them to generate new attributes for `endes_2019`. These attributes should be named as `var_labels` and `value_labels`. **Hint: Use `update` method.**

6. Get the min, max, sd, n_obs, n_missing for the following columns **total children ever born (V201)**, **Ideal number of children (V613)**, **Husbands education-single yrs (V715)**, and **Age at first marriage (V511)**. We want a dataframe with the following columns **Variables, Min, Max, Mean, N_obs, N_missing** and sort by the number of missing rows. **Hint: Use `describe` and `pivot` methods**

7. Use `endes_2019` data to generate a new object named `mean_key_vars` to find the mean of **total children ever born (V201)**, **Ideal number of children (V613)**, **Husbands education-single yrs (V715)**, and **Age at first marriage (V511)** by year and department **(V024)**. Name these columns as **mean_total_children, mean_ideal_children, mean_hb_yr_educ and mean_first_marriage**, respectively. **Hint: Use groupby and [this link](https://stackoverflow.com/questions/40901770/is-there-a-simple-way-to-change-a-column-of-yes-no-to-1-0-in-a-pandas-dataframe).**

8. Reshape `mean_key_vars` from wide to long. We want a dataframe with three columns **dpto, variables, values**. Name this object as `reshape_mean_key_vars`. **Hint: Use melt method**.

9. Replicate your answers for questions 7 and 8, but in one line of code. Make it the most simple as possible. **NO HINT**

10. Merge `reshape_mean_key_vars` with `endes_2019`. Name this object `final_result`. **Hint: Use merge.**

### Answer 1

First, we read the 3 sav files with read_spss and name them as instructed (`rec_1`, `rec_2` and `rec_3`). After that, we import the header and the label using sav.SavHeaderReader and name them as `new_var_labels1`, `new_var_labels2`, and `new_var_labels3`.

In [2]:
rec_1 = pd.read_spss( r"C:\Users\DELL\Documents\GitHub\Diplomado_PUCP\_data\endes\2019/REC0111.sav" )
rec_2 = pd.read_spss( r"C:\Users\DELL\Documents\GitHub\Diplomado_PUCP\_data\endes\2019/RE223132.sav" )
rec_3 = pd.read_spss( r"C:\Users\DELL\Documents\GitHub\Diplomado_PUCP\_data\endes\2019/RE516171.sav" )

In [3]:
import savReaderWriter as sav
with sav.SavHeaderReader( r"C:\Users\DELL\Documents\GitHub\Diplomado_PUCP\_data\endes\2019/REC0111.sav", ioUtf8=True) as header:
    var_labels1 = header.all()
    value_labels1 = var_labels1.valueLabels

In [4]:
value_labels1

{'V013': {0.0: 'De 12 a 14 años de edad',
  1.0: 'De 15 a 19 años de edad',
  2.0: 'De 20 a 24 años de edad',
  3.0: 'De 25 a 29 años de edad',
  4.0: 'De 30 a 34 años de edad',
  5.0: 'De 35 a 39 años de edad',
  6.0: 'De 40 a 44 años de edad',
  7.0: 'De 45 a 49 años de edad'},
 'V014': {1.0: 'Mes y año',
  2.0: 'Mes y edad - año imputado',
  3.0: 'Año y edad - mes imputado',
  4.0: 'Año y edad - año ignorado supera el año de entrevista',
  5.0: 'Año - edad y mes imputados',
  6.0: 'Edad - año y mes imputados',
  7.0: 'Mes - edad y año imputados',
  8.0: 'Ninguno - edad, mes y año imputados'},
 'V015': {1.0: 'Completa',
  2.0: 'Ausente',
  3.0: 'Aplazada',
  4.0: 'Rechazada',
  5.0: 'Incoompleta',
  6.0: 'Discapacitada',
  7.0: 'Otra'},
 'V018': {0.0: 'Sin calendario'},
 'V019': {0.0: 'Sin calendario'},
 'V020': {0.0: 'Toda la mujer muestra', 1.0: 'Alguna muestra casada'},
 'V023': {1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: ' Huanuco',
  11.0: ' Ica',
  12.0: ' Junin',
  13.0: ' La Libertad',
  14.0: ' Lambayeque',
  15.0: ' Lima',
  16.0: ' Loreto',
  17.0: ' Madre de Dios',
  18.0: ' Moquegua',
  19.0: ' Pasco',
  20.0: ' Piura',
  21.0: ' Puno',
  22.0: ' San Martin',
  23.0: ' Tacna',
  24.0: ' Tumbes',
  25.0: ' Ucayali'},
 'V024': {1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: ' Huanuco',
  11.0: ' Ica',
  12.0: ' Junin',
  13.0: ' La Libertad',
  14.0: ' Lambayeque',
  15.0: ' Lima',
  16.0: ' Loreto',
  17.0: ' Madre de Dios',
  18.0: ' Moquegua',
  19.0: ' Pasco',
  20.0: ' Piura',
  21.0: ' Puno',
  22.0: ' San Martin',
  23.0: ' Tacna',
  24.0: ' Tumbes',
  25.0: ' Ucayali'},
 'V025': {1.0: 'Urbano', 2.0: 'Rural'},
 'V026': {0.0: 'Capital, gran ciudad',
  1.0: 'Pequeña ciudad',
  2.0: 'Pueblo',
  3.0: 'Campo'},
 'V034': {0.0: 'El esposo no está en el hogar'},
 'V042': {0.0: 'No sabeleccionado', 1.0: 'Seleccionado'},
 'V043': {0.0: 'Mujer No sabeleccionada', 1.0: 'Mujer seleccionada'},
 'V044': {0.0: 'Mujer No sabeleccionada',
  1.0: 'Mujer seleccionada y entrevistada',
  2.0: 'Mujer seleccionada, pero la privacidad no es posible',
  3.0: 'Mujer seleccionada, pero no entrevistada'},
 'Q105DD': {31.0: '1', 98.0: 'No sabe el dia'},
 'V101': {1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: 'Huanuco',
  11.0: 'Ica',
  12.0: 'Junin',
  13.0: 'La Libertad',
  14.0: 'Lambayeque',
  15.0: 'Lima',
  16.0: 'Loreto',
  17.0: 'Madre de Dios',
  18.0: 'Moquegua',
  19.0: 'Pasco',
  20.0: 'Piura',
  21.0: 'Puno',
  22.0: 'San Martin',
  23.0: 'Tacna',
  24.0: 'Tumbes',
  25.0: 'Ucayali'},
 'V102': {1.0: 'Urbano', 2.0: 'Rural'},
 'V103': {0.0: 'Capital, gran ciudad',
  1.0: 'Ciudad',
  2.0: 'Pueblo',
  3.0: 'Campo',
  4.0: 'En el extranjero'},
 'V104': {95.0: 'Siempre',
  96.0: 'Visitante',
  97.0: 'Inconsistente',
  98.0: 'No sabe'},
 'V105': {0.0: 'Capital, gran ciudad',
  1.0: 'Ciudad',
  2.0: 'Pueblo',
  3.0: 'Campo',
  4.0: 'En el extranjero'},
 'V106': {0.0: 'Sin educación',
  1.0: 'Primario',
  2.0: 'Secundario',
  3.0: 'Mayor'},
 'V113': {11.0: 'Dentro de la vivienda',
  12.0: 'Fuera de la vivienda, pero dentro del edificio',
  13.0: 'Pilón/Grifo público',
  21.0: 'Pozo en la casa/patio/lote',
  22.0: 'Pozo Público',
  41.0: 'Manantial (puquio)',
  43.0: 'Río/Acequia/Laguna',
  51.0: 'Agua de lluvia',
  61.0: 'Camión tanque/Aguatero',
  71.0: 'Agua embotellada',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V115': {996.0: 'En los lugares', 997.0: 'No residente de jure'},
 'V116': {11.0: 'Vivienda interior',
  12.0: 'Vivienda exterior',
  21.0: 'Letrina ventilada',
  22.0: 'Pozo séptico',
  23.0: 'Latrina (ciego o negro)',
  24.0: 'Latrina sobre el río/lago',
  31.0: 'Río, canal',
  32.0: 'Sin servicio',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V119': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V120': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V121': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V122': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V123': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V124': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V125': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V127': {11.0: 'Tierra/arena',
  21.0: 'Madera (entablados)',
  31.0: 'Parquet o madera pulida',
  32.0: 'Làminas asfálticas, vinílicos o similares',
  33.0: 'Losetas, terrazos o similares',
  34.0: 'Cemento/ladrillo',
  96.0: 'Pona',
  97.0: 'Otro(pona)'},
 'V128': {11.0: 'Tablones/madera',
  12.0: 'Estera',
  13.0: 'Caña/bambu/pona/palma/troncos/tabique',
  21.0: 'Adobe o tapia tarrajeados',
  22.0: 'Quincha (caña con barro)',
  23.0: 'Piedra con barro',
  24.0: 'Cartón',
  31.0: 'Ladrillo o /Bloques de cemento',
  32.0: 'Piedra o sillar con cal o cemento',
  33.0: 'Tripley',
  41.0: 'Sin paredes',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V129': {11.0: 'Paja, hojas de palmera etc.',
  12.0: 'Estera',
  21.0: 'Caña o estera con torta de barro ',
  22.0: 'Cartón',
  31.0: 'Concreto armado',
  32.0: 'Madera ',
  33.0: 'Tejas',
  34.0: 'Plancha de calamina, fibra de cemento o similares ',
  41.0: 'Sin techo',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V130': {96.0: 'Otra'},
 'V131': {1.0: 'Quechua',
  2.0: 'Aimara',
  3.0: 'Ashaninka',
  4.0: 'Awajún/Aguaruna',
  5.0: 'Shipibo/Konibo',
  6.0: 'Shawi/Chayahuita',
  7.0: 'Matsigenka/ Machiguenga',
  8.0: 'Achuar',
  9.0: 'Otra lengua nativa u originaria',
  10.0: 'Castellano',
  11.0: 'Portugués',
  12.0: 'Otra lengua extranjera'},
 'V133': {97.0: 'Inconsistente'},
 'V134': {0.0: 'Capital, ciudad grande',
  1.0: 'Ciudad pequeña',
  2.0: 'Pueblo',
  3.0: 'Campo'},
 'V135': {1.0: 'Residente habitual', 2.0: 'Visitante'},
 'V139': {0.0: 'En el extranjero',
  1.0: 'Amazonas',
  2.0: 'Ancash',
  3.0: 'Apurimac',
  4.0: 'Arequipa',
  5.0: 'Ayacucho',
  6.0: 'Cajamarca',
  7.0: 'Callao',
  8.0: 'Cusco',
  9.0: 'Huancavelica',
  10.0: 'Huanuco',
  11.0: 'Ica',
  12.0: 'Junin',
  13.0: 'La Libertad',
  14.0: 'Lambayeque',
  15.0: 'Lima',
  16.0: 'Loreto',
  17.0: 'Madre de Dios',
  18.0: 'Moquegua',
  19.0: 'Pasco',
  20.0: 'Piura',
  21.0: 'Puno',
  22.0: 'San Martin',
  23.0: 'Tacna',
  24.0: 'Tumbes',
  25.0: 'Ucayali',
  97.0: 'No es residente habitual'},
 'V140': {1.0: 'Área urbana',
  2.0: 'Área rural',
  7.0: 'No es residente habitual'},
 'V141': {0.0: 'Capital, ciudad grande',
  1.0: 'Ciudad pequeña',
  2.0: 'Pueblo',
  3.0: 'Campo',
  7.0: 'No es residente habitual'},
 'V149': {0.0: 'Sin educación',
  1.0: 'Primaria incompleta',
  2.0: 'Primaria completa',
  3.0: 'Secundaria incompleta',
  4.0: 'Secundaria completa',
  5.0: 'Superior'},
 'V150': {1.0: 'Jefe del hogar',
  2.0: 'Esposa/esposo',
  3.0: 'Hijo/Hija',
  4.0: 'Yerno/Nuera ',
  5.0: 'Nieto/Nieta',
  6.0: 'Padre/Madre',
  7.0: 'Suegro/Suegra',
  8.0: 'Hermano/a',
  9.0: 'Conviviente',
  10.0: 'Otro pariente',
  11.0: 'Hijo adoptado/hijo de crianza',
  12.0: 'Sin parentesco',
  15.0: 'Empleada domésdtica',
  98.0: 'No sabe'},
 'V151': {1.0: 'Hombre', 2.0: 'Mujer'},
 'V152': {97.0: '97+', 98.0: 'NS'},
 'V153': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V155': {0.0: 'No puede leer',
  1.0: 'Puede leer sólo parte de la frase',
  2.0: 'Puede leer la frase ',
  3.0: 'No hay tarjeta en el idioma requerido',
  4.0: 'Ciega/problemas visuales'},
 'V156': {0.0: 'No', 1.0: 'Si'},
 'V157': {0.0: 'Nunca',
  1.0: 'De vez en cuando',
  2.0: 'Una vez por semana',
  3.0: 'Casi todos los días'},
 'V158': {0.0: 'Nunca',
  1.0: 'De vez en cuando',
  2.0: 'Una vez por semana',
  3.0: 'Casi todos los días'},
 'V159': {0.0: 'Nunca',
  1.0: 'De vez en cuando',
  2.0: 'Una vez por semana',
  3.0: 'Casi todos los días'},
 'V160': {0.0: 'No', 1.0: 'Si', 7.0: 'No es residente habitual'},
 'V161': {1.0: 'Electricidad',
  2.0: 'Gas Licuado (GLP)',
  3.0: 'Gas natural(Tuberia)',
  5.0: 'Kerosene',
  6.0: 'Carbón mineral',
  7.0: 'Carbon vegetal',
  8.0: 'Leña',
  9.0: 'Cañas/Arbustos (secos)',
  10.0: 'Residuos agricolas',
  11.0: 'Bosta',
  95.0: 'No cocina',
  96.0: 'Otro',
  97.0: 'No es residente habitual'},
 'V166': {0.0: 'Sin coloración  - 0 ppm (sin yodo)',
  7.0: 'Coloración tenue - 7 ppm',
  15.0: 'Coloración azul o morado - 15 ppm',
  30.0: 'Coloración morado oscuro - 30 ppm a más',
  994.0: 'No se pudo realizar la prueba ',
  995.0: 'No hay sal en el hogar'},
 'V167': {0.0: 'Ninguno'},
 'V168': {0.0: 'No', 1.0: 'Si'},
 'ML101': {0.0: 'Sin mosquitero',
  1.0: 'Solo mosquiteros tratados',
  2.0: 'Ambos mosquiteros tratados y no tratados',
  3.0: 'Solo mosquiteros no tratados'},
 'QD333_1': {1.0: 'Si', 2.0: 'No'},
 'QD333_2': {1.0: 'Si', 2.0: 'No'},
 'QD333_3': {1.0: 'Si', 2.0: 'No'},
 'QD333_4': {1.0: 'Si', 2.0: 'No'},
 'QD333_5': {1.0: 'Si', 2.0: 'No'},
 'QD333_6': {1.0: 'Si', 2.0: 'No'},
 'V190': {1.0: 'El más pobre',
  2.0: 'Pobrer',
  3.0: 'Medio',
  4.0: 'Rico',
  5.0: 'Más rico'},
 'mujeres12a49': {0.0: 'Mujeres de 12 a 14 de edad, nunca embarazadas',
  1.0: 'Mujeres de 12 a 49 de edad, alguna vez emabrazadas',
  2.0: 'Mujeres de 15 a 49 años de edad'}}

In [5]:
import savReaderWriter as sav
with sav.SavHeaderReader( r"C:\Users\DELL\Documents\GitHub\Diplomado_PUCP\_data\endes\2019/RE223132.sav", ioUtf8=True) as header:
    var_labels2 = header.all()
    value_labels2 = var_labels2.valueLabels

In [6]:
value_labels2

{'V213': {0.0: 'No o no está segura', 1.0: 'Sí'},
 'V215': {994.0: 'En la menopausia',
  995.0: 'Antes del último nacimiento',
  996.0: 'Nunca menstruado',
  997.0: 'Inconsistente',
  998.0: 'No sabe'},
 'V216': {0.0: 'No', 1.0: 'Si'},
 'V217': {1.0: 'Durante su periodo',
  2.0: 'Después de su período',
  3.0: 'En medio del ciclo',
  4.0: 'Antes del período',
  5.0: 'En cualquier momento',
  6.0: 'Otro',
  8.0: 'No sabe'},
 'V220': {6.0: '6+'},
 'V221': {996.0: 'Intervalo Negativo'},
 'V223': {7.0: 'Mes - fecha exacta', 8.0: 'Ninguno - fecha de colocación'},
 'V225': {1.0: 'En ese momento',
  2.0: 'Querìa esperar',
  3.0: 'No querìa tener (màs) hijas/hijos'},
 'V226': {994.0: 'En la menopausia',
  995.0: 'Antes del último nacimiento',
  996.0: 'Nunca menstruado',
  997.0: 'Inconsistente',
  998.0: 'No sabe'},
 'V227': {0.0: 'No marcado',
  1.0: 'N> int. desde el nacimiento',
  2.0: 'N + amen > intervalo',
  3.0: 'N, pero per no ret',
  4.0: '95, pero sin nacimiento',
  5.0: '95, pero per. devuelto',
  6.0: '96, pero por vuelta',
  7.0: 'N, last per Emba',
  8.0: '96, tuvo hijos',
  9.0: 'N, per antes ult nac'},
 'V228': {0.0: 'No', 1.0: 'Si'},
 'V229': {97.0: 'Inconsistente', 98.0: 'No Sabe'},
 'V230': {9997.0: 'Inconsistente', 9998.0: 'No Sabe'},
 'V231': {9997.0: 'Inconsistente', 9998.0: 'No Sabe'},
 'V232': {1.0: 'Mes y año',
  2.0: 'De calendario',
  5.0: 'Año',
  7.0: 'Mes',
  8.0: 'Ninguna'},
 'V233': {97.0: 'Inconsistente', 98.0: 'NS'},
 'V234': {0.0: 'No', 1.0: 'Si'},
 'V235': {0.0: 'No niño anterior'},
 'V237': {0.0: 'No', 1.0: 'Si'},
 'V239': {0.0: 'No', 1.0: 'Si'},
 'V240': {97.0: 'Inconsistente', 98.0: 'No sabe'},
 'V241': {9997.0: 'Inconsistente', 9998.0: 'No sabe'},
 'V242': {9997.0: 'Inconsistente', 9998.0: 'No sabe'},
 'V243': {1.0: 'Mes y año',
  2.0: 'De calendario',
  5.0: 'Año',
  7.0: 'Mes',
  8.0: 'Ninguna'},
 'V301': {0.0: 'No conoce ningún método',
  1.0: 'Sabe sólo folklórico',
  2.0: 'Sólo sabe trad. mes',
  3.0: 'Conoce el método moderno'},
 'V302': {0.0: 'Nunca usado',
  1.0: 'Otros metodos',
  2.0: 'Metodos tradicionales',
  3.0: 'Metodos modernos'},
 'V311': {4.0: '4 a más', 5.0: 'Nunca usado'},
 'V312': {0.0: 'No usando',
  1.0: 'Píldora',
  2.0: 'DIU',
  3.0: 'Inyección',
  4.0: 'Diafragma',
  5.0: 'Condón',
  6.0: 'Esterilización femenina',
  7.0: 'Esterilización masculina',
  8.0: 'Abstinencia periódica',
  9.0: 'Retiro',
  10.0: 'Otro',
  11.0: 'Norplant/Implantes',
  12.0: 'Abstinencia',
  13.0: 'Amenorrea por lactancia (MELA)',
  14.0: 'Condón femenino',
  15.0: 'Espuma, jalea, óvulos (vaginales)',
  16.0: 'Anticoncepción oral de emergencia',
  17.0: 'Método específico 1',
  18.0: 'Método específico 2',
  19.0: 'Método específico 3',
  20.0: 'Método específico 4'},
 'V313': {0.0: 'No hay método',
  1.0: 'Método folclórico',
  2.0: 'Método tradicional',
  3.0: 'Método moderno'},
 'V318': {1.0: 'Mes y año',
  5.0: 'Año - m imp, una calc',
  7.0: 'Mes - fecha de publicación',
  8.0: 'Ninguno - fecha de colocación',
  9.0: 'De calendario'},
 'V319': {1.0: 'menor de 2',
  2.0: 'de 2 a 3',
  3.0: 'de 4 a 5',
  4.0: 'de 6 a 7',
  5.0: 'de 8 a 9',
  6.0: 'de 10 a más'},
 'V320': {1.0: 'menor de 25',
  2.0: 'de 25 a 29',
  3.0: 'de 30 a 34',
  4.0: 'de 35 a 39',
  5.0: 'de 40 a 44',
  6.0: 'de 45 a 49'},
 'V321': {0.0: 'Soltero, antes del matrimonio',
  1.0: 'de 0 a 4',
  2.0: 'de 5 a 9',
  3.0: 'de 10 a 14',
  4.0: 'de 15 a 19',
  5.0: 'de 20 a 24',
  6.0: 'de 25 a más'},
 'V322': {5.0: 'de 5 a más'},
 'V323': {1.0: 'Microginon',
  2.0: 'Nordet',
  3.0: 'Lofemenal',
  4.0: 'Gynera',
  5.0: 'Ciclomex',
  6.0: 'Triciclomex',
  7.0: 'Femiane',
  8.0: 'Mercilon',
  9.0: 'Marvelon',
  10.0: 'Lindiol-e',
  11.0: 'Dione 35',
  12.0: 'Cilest',
  13.0: 'Triquilar',
  14.0: 'Trinordiol',
  15.0: 'Minigynon',
  16.0: 'Exluton',
  17.0: 'Ovrette',
  18.0: 'Ovral',
  19.0: 'Mirelle',
  20.0: 'Yasmin Drospyperona',
  21.0: 'Peldura',
  22.0: 'Anuletyc',
  23.0: 'Rigevidon',
  24.0: 'Oral Con-F',
  25.0: 'Canesa',
  26.0: 'Belara',
  27.0: 'Tri_Regol',
  93.0: 'Sin marca (H. FF.AA., FF.PP)',
  94.0: 'Sin marca (ESSALUD)',
  95.0: 'Sin marca (MINSA)',
  96.0: 'Otro',
  98.0: 'No sabe'},
 'V323A': {1.0: 'OK',
  2.0: 'Piel',
  3.0: 'Royal',
  4.0: 'Jontex',
  5.0: 'Contempo',
  6.0: 'Gens',
  7.0: 'LifeStyle',
  8.0: 'Sultan',
  9.0: 'Durex',
  10.0: 'Preventor',
  11.0: 'Hanson plans',
  12.0: 'Sensitive',
  13.0: 'Play boy',
  14.0: 'Lubritec',
  15.0: 'Pantera',
  16.0: 'Tex',
  17.0: 'Seohung',
  18.0: 'Aladan corporation',
  19.0: 'Vladi',
  20.0: 'Stalion',
  21.0: 'Latex',
  22.0: 'Pussy Cat',
  23.0: 'Sensación',
  24.0: 'Karex',
  25.0: 'Do it Loverly',
  26.0: 'Nonoxinol - 9',
  27.0: 'Famila 28',
  93.0: 'Sin marca (H. FF.AA., FF.PP)',
  94.0: 'Sin marca (ESSALUD)',
  95.0: 'Sin marca (MINSA)',
  96.0: 'Otro',
  98.0: 'No sabe'},
 'V325A': {9999995.0: 'Gratis', 9999998.0: 'No sabe'},
 'V326': {11.0: 'Hospital MINSA',
  12.0: 'Centro de salud MINSA',
  13.0: 'Puesto de salud MINSA',
  14.0: 'Promotor de salud MINSA ',
  15.0: 'Hospital ESSALUD',
  16.0: 'Policlìnico/Centro/Posta ESSALUD',
  17.0: 'Hospital/Otros de las FFAA & PNP',
  18.0: 'Hospital/Otro de la Municipalidad',
  19.0: 'Otro gobierno',
  21.0: 'Clínica particular',
  22.0: 'Farmacia/botica',
  23.0: 'Consultorio médico particular',
  24.0: 'Clínica/Posta de ONG',
  25.0: 'Promotor de ONG ',
  31.0: 'Tienda/supermercado/hostal',
  32.0: 'Hospital/Otro de la Iglesia',
  33.0: 'Amigos/parientes',
  95.0: 'Automedicación',
  96.0: 'Otro',
  98.0: 'No sabe'},
 'V327': {1.0: 'Hospital, Centro de Salud, Puesto de Salud, Policlínico del Gobierno',
  2.0: 'Promotor de Salud',
  3.0: 'Clínica/Posta/ Promotor ONG',
  4.0: 'Clínica/Consultorio médico particular',
  5.0: 'Farmacia/botica',
  6.0: 'Tienda, iglesia, amigo',
  7.0: 'Automedicación/Otro',
  8.0: 'No sabe',
  9.0: 'Otro gobierno'},
 'V337': {95.0: 'Todas cal {A core}',
  96.0: '96+ {B core}',
  997.0: 'Inconsistente',
  998.0: 'No sabe'},
 'V359': {1.0: 'Píldora',
  2.0: 'DIU',
  3.0: 'Inyecciones',
  4.0: 'Diafragma',
  5.0: 'Condón',
  6.0: 'Esterilización femenina',
  7.0: 'Esterilización masculina',
  8.0: 'Abstinencia periódica',
  9.0: 'Retiro',
  10.0: 'Otro',
  11.0: 'Norplant/Implantes',
  12.0: 'Abstinencia',
  13.0: 'Amenorrea por lactancia (MELA)',
  14.0: 'Condón femenino',
  15.0: 'Espuma, jalea, óvulos (vaginales)',
  16.0: 'Anticoncepción oral de emergencia',
  17.0: 'Método específico 1',
  18.0: 'Método específico 2',
  19.0: 'Método específico 3',
  20.0: 'Método específico 4'},
 'V360': {1.0: 'Quedó embarazada',
  2.0: 'Quería quedar embarazada',
  3.0: 'Marido desaprobó',
  4.0: 'Efectos secundarios',
  5.0: 'Motivos de salud',
  6.0: 'Acceso, disponibilidad',
  7.0: 'Deseaba método más efectivo',
  8.0: 'Uso inconveniente',
  9.0: 'Sexo poco frecuente/Marido ausente',
  10.0: 'Costo',
  11.0: 'Fatalista',
  12.0: 'Dificil quedar embarazda/menopausia',
  13.0: 'Disolución matrimonial',
  14.0: 'Otro',
  98.0: 'No sabe'},
 'V361': {1.0: 'Actualmente usando',
  2.0: 'Usado desde el último nacimiento',
  3.0: 'Usado antes del último nacimiento',
  4.0: 'Nunca usado'},
 'V362': {1.0: 'En los próximos 12 meses',
  2.0: 'Usar más tarde',
  3.0: 'No está seguro sobre el momento',
  4.0: 'No está seguro sobre el uso',
  5.0: 'No tiene la intención',
  6.0: 'Nunca tuve relaciones sexuales'},
 'V363': {1.0: 'Píldora',
  2.0: 'DIU',
  3.0: 'Inyección',
  4.0: 'Diafragma',
  5.0: 'Condón',
  6.0: 'Esterilización femenina',
  7.0: 'Esterilización masculina',
  8.0: 'Abstinencia periódica',
  9.0: 'Retiro',
  10.0: 'Otro',
  11.0: 'Norplant/Implantes',
  12.0: 'Abstinencia',
  13.0: 'Amenorrea por lactancia (MELA)',
  14.0: 'Condón femenino',
  15.0: 'Espuma, jalea, óvulos (vaginales)',
  16.0: 'Anticoncepción oral de emergencia',
  98.0: 'No sabe'},
 'V364': {1.0: 'Usando el método moderno',
  2.0: 'Usando el método tradicional',
  3.0: 'No-usuario tiene la intención de',
  4.0: 'No tiene la intención de',
  5.0: 'Nunca tuve relaciones sexuales'},
 'V367': {1.0: 'Entonces', 2.0: 'Esperar más', 3.0: 'No quería más'},
 'V372': {0.0: 'Paquete no visto', 1.0: 'Paquete visto'},
 'V372A': {0.0: 'Paquete no visto', 1.0: 'Paquete visto'},
 'V375A': {11.0: 'No casado',
  21.0: 'No tiene relaciones sexuales',
  22.0: 'Sexo poco frecuente',
  23.0: 'Menopausia',
  24.0: 'Infertilidad/Subfecundidad',
  25.0: 'Postparto/Lactancia',
  26.0: 'Quiere más hijas(os)',
  27.0: 'Embarazada',
  28.0: 'Histerectomìa',
  31.0: 'Entrevistada se opone',
  32.0: 'Esposo/compañero se opuso',
  33.0: 'Otros se oponen',
  34.0: 'Prohibición religiosa',
  41.0: 'No conoce ningún método',
  42.0: 'No conoce ninguna fuente',
  51.0: 'Problemas de salud',
  52.0: 'Miedo a efectos secundarios',
  53.0: 'Falta de acceso',
  54.0: 'Muy costoso',
  55.0: 'Uso inconveniente',
  56.0: 'Interfiere con procesos normales del cuerpo',
  96.0: 'Otro',
  98.0: 'No sabe'},
 'V376': {11.0: 'No casado',
  22.0: 'Sexo poco frecuente',
  23.0: 'Menopáusica/histerectomizada',
  24.0: 'Infertilidad mujer',
  25.0: 'Infertilidad hombre',
  26.0: 'Quiere más hijas(os)',
  31.0: 'Entrevistada se opone',
  32.0: 'Esposo/compañero se opuso',
  33.0: 'Otros se oponen',
  34.0: 'Prohibición religiosa',
  41.0: 'No conoce ningún método',
  42.0: 'No conoce ninguna fuente',
  51.0: 'Problemas de salud',
  52.0: 'Miedo a efectos secundarios',
  53.0: 'Falta de acceso',
  54.0: 'Muy costoso',
  55.0: 'Uso inconveniente',
  56.0: 'Interfiere con procesos normales del cuerpo',
  96.0: 'Otro',
  98.0: 'No sabe'},
 'V376A': {0.0: 'No', 1.0: 'Si', 8.0: 'No sabe'},
 'V379': {11.0: 'Hospital MINSA',
  12.0: 'Centro de salud MINSA',
  13.0: 'Puesto de salud MINSA',
  14.0: 'Trabajadora sanitaria MINSA',
  15.0: 'Hospital ESSALUD',
  16.0: 'Centro/Correo ESSALUD',
  17.0: 'Campaña/feria',
  18.0: 'Otro gobierno',
  21.0: 'Clínica privada',
  22.0: 'Farmacia',
  23.0: 'Médico privado',
  24.0: 'Clínica/FP post ONG',
  25.0: 'ONG de trabajadores de la salud',
  31.0: 'Tienda/supermercado',
  32.0: 'Iglesia',
  33.0: 'Amigos/parientes',
  95.0: 'Automedicación',
  96.0: 'Otro',
  98.0: 'No sabe'},
 'V380': {1.0: 'Govt Clinical/Pharm',
  2.0: 'Casa de Gobierno/Comm liv',
  3.0: 'ONG',
  4.0: 'Private Clin/Deliv',
  5.0: 'Farmacia Privada',
  6.0: 'Tienda, iglesia, amigo',
  7.0: 'Otro',
  8.0: 'No sabe'},
 'V384A': {0.0: 'No', 1.0: 'Si'},
 'V384B': {0.0: 'No', 1.0: 'Si'},
 'V384C': {0.0: 'No', 1.0: 'Si'},
 'V393': {0.0: 'No', 1.0: 'Si'},
 'V394': {0.0: 'No', 1.0: 'Si'},
 'V395': {0.0: 'No', 1.0: 'Si'},
 'V3A00A': {0.0: 'No', 1.0: 'Hospital del gobierno'},
 'V3A00B': {0.0: 'No', 1.0: 'Centro de salud del gobierno'},
 'V3A00C': {0.0: 'No', 1.0: 'Puesto de salud del gobierno'},
 'V3A00D': {0.0: 'No', 1.0: 'Clínica móvil pública'},
 'V3A00E': {0.0: 'No', 1.0: 'Trabajador de salud comunitario'},
 'V3A00F': {0.0: 'No', 1.0: 'CS sector público'},
 'V3A00G': {0.0: 'No', 1.0: 'CS sector público'},
 'V3A00H': {0.0: 'No', 1.0: 'CS sector público'},
 'V3A00I': {0.0: 'No', 1.0: 'Other sector público'},
 'V3A00J': {0.0: 'No', 1.0: 'Hospítal/clínica particular'},
 'V3A00K': {0.0: 'No', 1.0: 'Famacia privada'},
 'V3A00L': {0.0: 'No', 1.0: 'Doctor privado'},
 'V3A00M': {0.0: 'No', 1.0: 'Clínica móvil privada'},
 'V3A00N': {0.0: 'No', 1.0: 'Trabajador de salud comunitario'},
 'V3A00O': {0.0: 'No', 1.0: 'CS sector privado'},
 'V3A00P': {0.0: 'No', 1.0: 'CS sector privado'},
 'V3A00Q': {0.0: 'No', 1.0: 'CS sector privado'},
 'V3A00R': {0.0: 'No', 1.0: 'Otro sector privado'},
 'V3A00S': {0.0: 'No', 1.0: 'Tienda'},
 'V3A00T': {0.0: 'No', 1.0: 'Práctica tradicional'},
 'V3A00U': {0.0: 'No', 1.0: 'CS otro sector privavdo'},
 'V3A00V': {0.0: 'No', 1.0: 'CS otro sector privado'},
 'V3A00W': {0.0: 'No', 1.0: 'CS otro sector privado'},
 'V3A00X': {0.0: 'No', 1.0: 'Otro'},
 'V3A00Y': {0.0: 'No: conoce una fuente', 1.0: 'Sí: no conoce ninguna fuente'},
 'V3A00Z': {0.0: 'No', 1.0: 'Si'},
 'V3A01': {0.0: 'No', 1.0: 'Si', 8.0: 'No sabe'},
 'V3A02': {0.0: 'No', 1.0: 'Si'},
 'V3A03': {0.0: 'No', 1.0: 'Si'},
 'V3A04': {0.0: 'No', 1.0: 'Si'},
 'V3A05': {0.0: 'No', 1.0: 'Si'},
 'V3A06': {0.0: 'No', 1.0: 'Si'},
 'V3A07': {11.0: 'Hospital MINSA',
  12.0: 'Centro de salud MINSA',
  13.0: 'Puesto de salud MINSA',
  14.0: 'Promotor de salud  MINSA',
  15.0: 'Hospital ESSALUD',
  16.0: 'Policlìnico/Centro/Posta ESSALUD',
  17.0: 'Hospital/Otros de las FFAA & PNP',
  18.0: 'Hospital/Otro de la Municipalidad',
  19.0: 'Otro gobierno',
  21.0: 'Clínica particular',
  22.0: 'Farmacia/botica',
  23.0: 'Consultorio médico particular',
  24.0: 'Clínica /Posta de ONG',
  25.0: 'Promotores de ONG',
  31.0: 'Tienda/supermercado/hostal',
  32.0: 'Hospital/otro de la Iglesia',
  33.0: 'Amigos/parientes',
  95.0: 'Automedicación',
  96.0: 'Otro',
  97.0: 'No se pregunto fuente',
  98.0: 'No sabe'},
 'V3A08A': {0.0: 'No', 1.0: 'No en unión'},
 'V3A08B': {0.0: 'No', 1.0: 'No tiene relaciones sexuales'},
 'V3A08C': {0.0: 'No', 1.0: 'Sexo poco frecuente'},
 'V3A08D': {0.0: 'No', 1.0: 'Menopáusica/histerectomizada'},
 'V3A08E': {0.0: 'No', 1.0: 'Infertilidad de la mujer'},
 'V3A08F': {0.0: 'No', 1.0: 'Amenorrea posparto'},
 'V3A08G': {0.0: 'No', 1.0: 'Lactancia'},
 'V3A08H': {0.0: 'No', 1.0: 'Fatalista'},
 'V3A08I': {0.0: 'No', 1.0: 'Entrevistada se opone'},
 'V3A08J': {0.0: 'No', 1.0: 'Esposo/compañero se opone'},
 'V3A08K': {0.0: 'No', 1.0: 'Otros se oponen'},
 'V3A08L': {0.0: 'No', 1.0: 'Prohibición religiosa'},
 'V3A08M': {0.0: 'No', 1.0: 'No conoce ningún método'},
 'V3A08N': {0.0: 'No', 1.0: 'No conoce ninguna fuente'},
 'V3A08O': {0.0: 'No', 1.0: 'Problemas de salud'},
 'V3A08P': {0.0: 'No', 1.0: 'Miedo a los efectos secundarios'},
 'V3A08Q': {0.0: 'No', 1.0: 'Falta de acceso/demasiado lejos'},
 'V3A08R': {0.0: 'No', 1.0: 'Muy costoso'},
 'V3A08S': {0.0: 'No', 1.0: 'Uso inconveniente'},
 'V3A08T': {0.0: 'No', 1.0: 'Interfiere con procesos normales del cuerpo'},
 'V3A08U': {0.0: 'No', 1.0: 'Infertilidad masculina'},
 'V3A08V': {0.0: 'No', 1.0: 'CS'},
 'V3A08W': {0.0: 'No', 1.0: 'CS'},
 'V3A08X': {0.0: 'No', 1.0: 'Otra'},
 'V3A08Z': {0.0: 'No', 1.0: 'No sabe'},
 'V3A09A': {998.0: 'No sabe'},
 'V3A09B': {998.0: 'No sabe'},
 'V305_01': {0.0: 'No', 1.0: 'Sí'},
 'V305_02': {0.0: 'No', 1.0: 'Sí'},
 'V305_03': {0.0: 'No', 1.0: 'Sí'},
 'V305_05': {0.0: 'No', 1.0: 'Sí'},
 'V305_06': {0.0: 'No', 1.0: 'Sí'},
 'V305_07': {0.0: 'No', 1.0: 'Sí'},
 'V305_08': {0.0: 'No', 1.0: 'Sí'},
 'V305_09': {0.0: 'No', 1.0: 'Sí'},
 'V305_10': {0.0: 'No', 1.0: 'Sí'},
 'V305_11': {0.0: 'No', 1.0: 'Sí'},
 'V305_13': {0.0: 'No', 1.0: 'Sí'},
 'V305_14': {0.0: 'No', 1.0: 'Sí'},
 'V305_15': {0.0: 'No', 1.0: 'Sí'},
 'V305_16': {0.0: 'No', 1.0: 'Sí'},
 'V307_01': {0.0: 'No', 1.0: 'Sí'},
 'V307_02': {0.0: 'No', 1.0: 'Sí'},
 'V307_03': {0.0: 'No', 1.0: 'Sí'},
 'V307_04': {0.0: 'No', 1.0: 'Sí'},
 'V307_05': {0.0: 'No', 1.0: 'Sí'},
 'V307_06': {0.0: 'No', 1.0: 'Sí'},
 'V307_07': {0.0: 'No', 1.0: 'Sí'},
 'V307_08': {0.0: 'No', 1.0: 'Sí'},
 'V307_09': {0.0: 'No', 1.0: 'Sí'},
 'V307_10': {0.0: 'No', 1.0: 'Sí'},
 'V307_11': {0.0: 'No', 1.0: 'Sí'},
 'V307_12': {0.0: 'No', 1.0: 'Sí'},
 'V307_13': {0.0: 'No', 1.0: 'Sí'},
 'V307_14': {0.0: 'No', 1.0: 'Sí'},
 'V307_15': {0.0: 'No', 1.0: 'Sí'},
 'V307_16': {0.0: 'No', 1.0: 'Sí'},
 'QI302_05A': {1.0: 'Sí', 2.0: 'No'},
 'QI302_05B': {1.0: 'Sí', 2.0: 'No'}}

In [7]:
import savReaderWriter as sav
with sav.SavHeaderReader( r"C:\Users\DELL\Documents\GitHub\Diplomado_PUCP\_data\endes\2019/RE516171.sav", ioUtf8=True) as header:
    var_labels3 = header.all()
    value_labels3 = var_labels3.valueLabels

In [8]:
value_labels3

{'V501': {0.0: 'Nunca casada',
  1.0: 'Casado',
  2.0: 'Viviendo juntos',
  3.0: 'Viuda',
  4.0: 'Divorciada',
  5.0: 'No viven juntos'},
 'V502': {0.0: 'Nunca casada',
  1.0: 'Actualmente casada',
  2.0: 'Anteriormente casada'},
 'V503': {1.0: 'Una vez', 2.0: 'Mas de una vez'},
 'V504': {1.0: 'Vive con ella', 2.0: 'Vive en otro sitio'},
 'V505': {0.0: 'No otras esposas', 98.0: 'No sabe'},
 'V506': {98.0: 'No sabe'},
 'V510': {1.0: 'Tiene mes y año',
  2.0: 'Tiene mes y edad - imputa año',
  3.0: 'Tiene año y edad - imputa mes',
  5.0: 'Tiene año - imputa mes',
  6.0: 'Tiene edad - imputa mes año',
  7.0: 'Tiene mes - imputa año',
  8.0: 'Ninguno - imputa todo'},
 'V513': {0.0: 'Nunca casada',
  1.0: 'De 0 a 4 años',
  2.0: 'De 5 a 9 años',
  3.0: 'De 10 a 14 años',
  4.0: 'De 15 a 19 años',
  5.0: 'De 20 a 24 años',
  6.0: 'De 25 a 29 años',
  7.0: 'De 30 a más años'},
 'V525': {0.0: 'Nunca tuvo relaciones sexuales', 96.0: 'En la primera union'},
 'V527': {100.0: 'Menos de un día',
  101.0: 'Días:',
  201.0: 'Semanas:',
  301.0: 'Meses:',
  401.0: 'Años:'},
 'V528': {31.0: '31 ó más días'},
 'V529': {997.0: 'Inconsistente'},
 'V530': {0.0: 'Sin marcador',
  1.0: 'N> int. desde el nacimiento',
  2.0: 'N + abst. > intervalo',
  3.0: 'N, pero el sexo no res.',
  4.0: '96, pero sin nacimiento',
  5.0: '96, pero act emb',
  6.0: '96, pero reanudó el sexo',
  7.0: 'N, último sexo antes de',
  8.0: 'N, inconsis 4 semanas',
  9.0: 'N, sex bef last birt'},
 'V531': {0.0: 'No tuve relaciones sexuales',
  97.0: 'Inconsistente',
  98.0: 'No sabe'},
 'V532': {0.0: 'Sin bandera',
  1.0: 'Despues de la entrevista',
  2.0: 'Después de concep> = 1 año',
  3.0: 'Después de concep <1 año',
  4.0: 'En marr, nunca marr',
  5.0: 'En marr, despues de concep',
  6.0: 'Despues del matrimonio'},
 'V535': {0.0: 'No', 1.0: 'Sí, estuvo casada', 2.0: 'Sí, convivió'},
 'V536': {0.0: 'Nunca tuvo relaciones sexuales',
  1.0: 'Activo en las últimas 4 semanas',
  2.0: 'No activo en las últimas 4 semanas - abstinencia postparto',
  3.0: 'No activo en las últimas 4 semanas - no abstinencia postparto'},
 'V537': {60.0: '60 meses o más', 97.0: 'Inconsistente'},
 'V538': {1.0: 'Muerte/viudez', 2.0: 'Divorcio', 3.0: 'Separación'},
 'V539': {1.0: 'Informante',
  2.0: 'Otra esposa',
  3.0: 'Hijos del cónyuge',
  4.0: 'Familia del cónyuge',
  6.0: 'Otro',
  7.0: 'Sin propiedad'},
 'V540': {0.0: 'No', 1.0: 'Sí'},
 'V541': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe/insegura'},
 'V602': {1.0: 'Tener un/otro hijo',
  2.0: 'No sabe/insegura',
  3.0: 'No más/ninguno',
  4.0: 'Esterilizada',
  5.0: 'Infertilidad'},
 'V603': {993.0: 'Despues del matrimonio',
  994.0: 'Pronto, ahora',
  996.0: 'Otro, No numérico',
  998.0: 'No sabe'},
 'V604': {0.0: 'De 0 a 11 meses',
  1.0: '1 año',
  2.0: '2 años',
  3.0: '3 años',
  4.0: '4 años',
  5.0: '5 años',
  6.0: '6 ó más años',
  7.0: 'No numérico',
  8.0: 'No sabe'},
 'V605': {1.0: 'Quiere dentro de 2 años',
  2.0: 'Quiere después de 2 ó más años',
  3.0: 'Quiere, no está seguro de tiempo',
  4.0: 'Indecisa',
  5.0: 'No quiere mas',
  6.0: 'Esterilizada',
  7.0: 'Infértil'},
 'V613': {96.0: 'Respuesta no numérica'},
 'V614': {6.0: '6 ó más', 7.0: 'Respuesta no numérica'},
 'V616': {993.0: 'Despues del matrimonio',
  994.0: 'Pronto/ahora',
  995.0: 'No puede quedar embarazada',
  996.0: 'Otro',
  998.0: 'No sabe'},
 'V621': {1.0: 'Ambos quieren el mismo número',
  2.0: 'Quiere más hijas/hijos',
  3.0: 'Quiere menos hijas/hijos',
  8.0: 'No sabe'},
 'V623': {0.0: 'Fértil',
  1.0: 'Embarazada',
  2.0: 'Amenorrea',
  3.0: 'Infértil, menopausia'},
 'V624': {0.0: 'Nunca tuvo relaciones sexuales',
  1.0: 'NeceSIDAd insatisfecha de espacio',
  2.0: 'NeceSIDAd insatisfecha de limite',
  3.0: 'Uso de espacio',
  4.0: 'Uso de límite',
  5.0: 'Falla de espacio',
  6.0: 'Falla de límite',
  7.0: 'Deseo de nacimiento <2 años',
  8.0: 'No sexo, quiere esperar',
  9.0: 'Infértil, menopausia'},
 'V625': {0.0: 'Fértil',
  1.0: 'Embarazada',
  2.0: 'Amenorreica',
  3.0: 'Infértil, menopausia'},
 'V626': {0.0: 'Nunca tuve relaciones sexuales',
  1.0: 'NeceSIDAd insatisfecha de espacio',
  2.0: 'NeceSIDAd insatisfecha de limitar',
  3.0: 'Uso de espacio',
  4.0: 'Uso de límite',
  5.0: 'Falla de espacio',
  6.0: 'Falla de límite',
  7.0: 'Deseo de nacimiento <2 años',
  8.0: 'No sexo, quiere esperar',
  9.0: 'Infértil, menopausia'},
 'V627': {96.0: 'Otro'},
 'V628': {96.0: 'Otro'},
 'V629': {96.0: 'Otro'},
 'V631': {1.0: 'Un gran problema',
  2.0: 'Un pequeño problema',
  3.0: 'No seria problema',
  4.0: 'No puede quedar embarazada/No tiene relaciones sexuales'},
 'V632': {1.0: 'Entrevistada principalmente',
  2.0: 'Esposo, compañero principalmente',
  3.0: 'Decisión conjunta',
  6.0: 'Otro'},
 'V633A': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V633B': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V633C': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V633D': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V633E': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V633F': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V633G': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V634': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V701': {0.0: 'Sin educación',
  1.0: 'Primario',
  2.0: 'Secundario',
  3.0: 'Superior',
  8.0: 'No sabe'},
 'V702': {98.0: 'No sabe'},
 'V704': {0.0: 'Otro, no trabaja, no especificada',
  1.0: 'Fuerzas Armadas',
  2.0: 'Fuerzas Policiales',
  5.0: 'Pensionado, Jubilado, Rentista, Estudiante.',
  11.0: 'Miembros del Poder Ejecutivo y de los Cuerpos Legislativos del Personal',
  12.0: 'Directores de Empresa (con 3 o más Directores)',
  13.0: 'Directores de la Educación',
  14.0: 'Gerente de Pequeñas Empresas (Talleres)',
  21.0: 'Profesionales de las Ciencias Físicas, Químicas, Matemáticas e Ingeniería, Civil, Arquitecto',
  22.0: 'Ingenierías (diferentes a Ing. Civil)',
  23.0: 'Profesionales de las Ciencias Biológicas, la Medicina y la Salud.',
  24.0: 'Profesores (Maestros y/o Pedagogos), Auxiliar de Educación',
  25.0: 'Profesionales de Derecho, Ciencias Económicas Administrativas',
  26.0: 'Bibliotecario, Ciencias Sociales, Periodistas, Psicólogos',
  27.0: 'Profesionales de las Artes, Escultura, Música y Afines',
  28.0: 'Otros Profesionales y Trabajadores Varios: Turismo y Hotelería, Relacionista Público, Diplomáticos, Sacerdotes',
  31.0: 'Técnicos de Nivel Medio en Ciencias Físicas, Químicas, Matemáticas e Ingeniería',
  32.0: 'Operadores de Equipos Especializados, Fotógrafos y Afines',
  33.0: 'Técnicos en Navegación Marítima y Aeronáutica e Inspectores de Seguridad, Salud y Control de Calidad',
  34.0: 'Técnicos de Nivel Medio y Trabajadores Asimilados de las Ciencias Biológicas',
  35.0: 'Técnicos de Nivel Medio y Trabajadores Asimilados de la Medicina y la Salud, Aplicación de Inyectables, Enfermera Técnic',
  36.0: 'Jefes de Ventas y Técnicos en Administración, Contabilidad, Economía y Operaciones Financieras y Comerciales (Afines), T',
  37.0: 'Agentes de Servicios Administrativos (Asesor Previsional AFP)',
  38.0: 'Asistentes y Auxiliares en la Administración',
  39.0: 'Artistas Afines, Trabajadores del Espectáculo, Atletas y Auxiliares de Cultos Religiosos',
  41.0: 'Jefes de Dependencias Administrativas, Oficinistas, Secretarias, Digitador, Tipeos por Computadora',
  42.0: 'Personal Administrativo y Empleados Afines',
  43.0: 'Jefes de Servicios de Transportes y Trabajadores Afines, Controlador de Microbús',
  44.0: 'Jefes de Servicios de Correos; Empleados de Bibliotecas, de Imprenta y Afines, Carteros, Mensajeros',
  45.0: 'Cajeros, Recepcionistas y Trabajadores Asimilados, Telefonista, Cobradores (Excluye el Cobrador de Microbús)',
  46.0: 'Empleados de Oficina en Operación de Campo y Otros Oficinistas, Encuestadores, Registradores, Supervisor de Campo, Auxil',
  51.0: 'Personal al Servicio Directo de los Pasajeros, Guía de Turismo, Aeromoza',
  52.0: 'Jefes, Ecónomas y Mayordomos, Azafata, Mozo',
  53.0: 'Trabajadores de los Cuidados Personales,  Auxiliar de Enfermería, Ayudante en Consultorio Dental',
  54.0: 'Peluqueros, Especialistas en Tratamiento de Belleza y Trabajadores Asimilados',
  55.0: 'Trabajadores de Servicios Varios, Modelos, Tramitador de Documentos para Sepelio, Cartomancia',
  56.0: 'Personal de los Servicios de Protección y Seguridad, Bombero, Policía Municipal, Serenazgo, Policía Particular',
  57.0: 'Comerciantes Vendedores al Por Mayor y Por Menor, Vendedor en Kiosko, Vendedora en Puesto de Mercado, Demostrador de Art',
  58.0: 'Comerciantes y Vendedores (No ambulatorio), No Clasificados Bajo otros Epígrafes, Vendedor Comisionista, Vendedor, Agent',
  61.0: 'Agricult. (Expl.) y Trab. Calificados de Cultivos Extensivos: Peones de Labranza y Peones Agropecuarios,Peones Forestale',
  62.0: 'Criadores y Trabajadores Pecuarios Calificados de Cría de Animales para el Mercado y Afines',
  63.0: 'Pescadores, Cazadores y Tramperos Peones de la Pesca, la Caza y la Trampa',
  71.0: 'Mineros, Canteros, Sondistas y Trabajadores Asimilados',
  72.0: 'Obreros de Tratamiento de la Madera y de la Fabricación de Papel',
  73.0: 'Obreros de los Tratamientos Químicos y Trabajadores Asimilados',
  74.0: 'Hilanderos, Tejedores, Tintoreros y Trabajadores Asimilados',
  75.0: 'Obreros de la Preparación, Curtido y Tratamiento de Pieles',
  76.0: 'Obreros de la Preparación de Alimentos y Bebidas Degollador de Reses, Cortador de Carne, Panadero, Pastelero',
  77.0: 'Obreros de Calzado, Sastres, Modistos, Peleteros, Ebanistas, Tapiceros y Otros Afines, Sombrerero',
  78.0: 'Obreros, Mecánicos y Ajustadores de Metales, Equipos Eléctricos, Electrónicos y de Vehículos de Motor, Mecánico de Vehíc',
  79.0: 'Ajustadores, Montadores e Instaladores de Máquinas e Instrumentos de Precisión, Relojeros, Mecánicos, Joyeros y Plateros',
  81.0: 'Obreros de la Fabricación de Productos de Caucho y Plástico, Instrumentos de Música, Pintores y Conductores de Maquinari',
  82.0: 'Confeccionadores de Productos de Papel y Cartón',
  83.0: 'Obreros de las Artes Gráficas, Fotógrafo (Excluye Fotógrafo Ambulante)',
  84.0: 'Obreros Manufactureros y Trabajadores Asimilados No Clasificados en Otras Clasificaciones',
  85.0: 'Pintores de Edificios, de Decoración de Teatro, de Construcción Metálica, de Autos, de Pincel y de Rodillo',
  86.0: 'Obreros en la Construcción, Albañil, Carpintero, Ebanista',
  87.0: 'Operadores de Máquinas Agrícolas, Fijas y de Instalaciones Similares y Obreros de la Manipulación de Mercancías y Materi',
  88.0: 'Conductores de Medios de Transporte y Personas en Ocupaciones Afines (Excepto a Pedal y a Mano), Chofer, Taxista',
  91.0: 'Vendedores Ambulantes',
  93.0: 'Cobradores y Vendedores de los Servicios de Transporte y Afines, Cobrador de Microbús',
  94.0: 'Personal Doméstico, Limpiadores, Lavanderos, Planchadores y Afines, Conserje, Limpiabotas, Fotógrafo Ambulante, Jardiner',
  95.0: 'Mensajeros, Repartidores, Porteros y Afines, Lector de Medidores, Guardián',
  96.0: 'Recolectores de Basura',
  98.0: 'Peones de la Minería, Suministro Electricidad, Gas y Agua, la Construcción, la Industria Manufacturera y el Transporte'},
 'V705': {0.0: 'No trabaja',
  1.0: 'Profesional, Técnico, Gerente',
  2.0: 'Eclesiástico',
  3.0: 'Ventas',
  4.0: 'Agricultor, trabajador independiente',
  5.0: 'Agricultor, empleado',
  6.0: 'Empleado del hogar',
  7.0: 'Servicios',
  8.0: 'Habilidades manuales',
  9.0: 'Sin habilidades manuales'},
 'V714': {0.0: 'No', 1.0: 'Sí'},
 'V714A': {0.0: 'No', 1.0: 'Sí'},
 'V715': {98.0: 'No sabe'},
 'V716': {0.0: 'Otro, no trabaja, no especificada',
  1.0: 'Fuerzas Armadas',
  2.0: 'Fuerzas Policiales',
  5.0: 'Pensionado, Jubilado, Rentista, Estudiante.',
  11.0: 'Miembros del Poder Ejecutivo y de los Cuerpos Legislativos del Personal',
  12.0: 'Directores de Empresa (con 3 o más Directores)',
  13.0: 'Directores de la Educación',
  14.0: 'Gerente de Pequeñas Empresas (Talleres)',
  21.0: 'Profesionales de las Ciencias Físicas, Químicas, Matemáticas e Ingeniería, Civil, Arquitecto',
  22.0: 'Ingenierías (diferentes a Ing. Civil)',
  23.0: 'Profesionales de las Ciencias Biológicas, la Medicina y la Salud.',
  24.0: 'Profesores (Maestros y/o Pedagogos), Auxiliar de Educación',
  25.0: 'Profesionales de Derecho, Ciencias Económicas Administrativas',
  26.0: 'Bibliotecario, Ciencias Sociales, Periodistas, Psicólogos',
  27.0: 'Profesionales de las Artes, Escultura, Música y Afines',
  28.0: 'Otros Profesionales y Trabajadores Varios: Turismo y Hotelería, Relacionista Público, Diplomáticos, Sacerdotes',
  31.0: 'Técnicos de Nivel Medio en Ciencias Físicas, Químicas, Matemáticas e Ingeniería',
  32.0: 'Operadores de Equipos Especializados, Fotógrafos y Afines',
  33.0: 'Técnicos en Navegación Marítima y Aeronáutica e Inspectores de Seguridad, Salud y Control de Calidad',
  34.0: 'Técnicos de Nivel Medio y Trabajadores Asimilados de las Ciencias Biológicas',
  35.0: 'Técnicos de Nivel Medio y Trabajadores Asimilados de la Medicina y la Salud, Aplicación de Inyectables, Enfermera Técnic',
  36.0: 'Jefes de Ventas y Técnicos en Administración, Contabilidad, Economía y Operaciones Financieras y Comerciales (Afines), T',
  37.0: 'Agentes de Servicios Administrativos (Asesor Previsional AFP)',
  38.0: 'Asistentes y Auxiliares en la Administración',
  39.0: 'Artistas Afines, Trabajadores del Espectáculo, Atletas y Auxiliares de Cultos Religiosos',
  41.0: 'Jefes de Dependencias Administrativas, Oficinistas, Secretarias, Digitador, Tipeos por Computadora',
  42.0: 'Personal Administrativo y Empleados Afines',
  43.0: 'Jefes de Servicios de Transportes y Trabajadores Afines, Controlador de Microbús',
  44.0: 'Jefes de Servicios de Correos; Empleados de Bibliotecas, de Imprenta y Afines, Carteros, Mensajeros',
  45.0: 'Cajeros, Recepcionistas y Trabajadores Asimilados, Telefonista, Cobradores (Excluye el Cobrador de Microbús)',
  46.0: 'Empleados de Oficina en Operación de Campo y Otros Oficinistas, Encuestadores, Registradores, Supervisor de Campo, Auxil',
  51.0: 'Personal al Servicio Directo de los Pasajeros, Guía de Turismo, Aeromoza',
  52.0: 'Jefes, Ecónomas y Mayordomos, Azafata, Mozo',
  53.0: 'Trabajadores de los Cuidados Personales,  Auxiliar de Enfermería, Ayudante en Consultorio Dental',
  54.0: 'Peluqueros, Especialistas en Tratamiento de Belleza y Trabajadores Asimilados',
  55.0: 'Trabajadores de Servicios Varios, Modelos, Tramitador de Documentos para Sepelio, Cartomancia',
  56.0: 'Personal de los Servicios de Protección y Seguridad, Bombero, Policía Municipal, Serenazgo, Policía Particular',
  57.0: 'Comerciantes Vendedores al Por Mayor y Por Menor, Vendedor en Kiosko, Vendedora en Puesto de Mercado, Demostrador de Art',
  58.0: 'Comerciantes y Vendedores (No ambulatorio), No Clasificados Bajo otros Epígrafes, Vendedor Comisionista, Vendedor, Agent',
  61.0: 'Agricult. (Expl.) y Trab. Calificados de Cultivos Extensivos: Peones de Labranza y Peones Agropecuarios,Peones Forestale',
  62.0: 'Criadores y Trabajadores Pecuarios Calificados de Cría de Animales para el Mercado y Afines',
  63.0: 'Pescadores, Cazadores y Tramperos Peones de la Pesca, la Caza y la Trampa',
  71.0: 'Mineros, Canteros, Sondistas y Trabajadores Asimilados',
  72.0: 'Obreros de Tratamiento de la Madera y de la Fabricación de Papel',
  73.0: 'Obreros de los Tratamientos Químicos y Trabajadores Asimilados',
  74.0: 'Hilanderos, Tejedores, Tintoreros y Trabajadores Asimilados',
  75.0: 'Obreros de la Preparación, Curtido y Tratamiento de Pieles',
  76.0: 'Obreros de la Preparación de Alimentos y Bebidas Degollador de Reses, Cortador de Carne, Panadero, Pastelero',
  77.0: 'Obreros de Calzado, Sastres, Modistos, Peleteros, Ebanistas, Tapiceros y Otros Afines, Sombrerero',
  78.0: 'Obreros, Mecánicos y Ajustadores de Metales, Equipos Eléctricos, Electrónicos y de Vehículos de Motor, Mecánico de Vehíc',
  79.0: 'Ajustadores, Montadores e Instaladores de Máquinas e Instrumentos de Precisión, Relojeros, Mecánicos, Joyeros y Plateros',
  81.0: 'Obreros de la Fabricación de Productos de Caucho y Plástico, Instrumentos de Música, Pintores y Conductores de Maquinari',
  82.0: 'Confeccionadores de Productos de Papel y Cartón',
  83.0: 'Obreros de las Artes Gráficas, Fotógrafo (Excluye Fotógrafo Ambulante)',
  84.0: 'Obreros Manufactureros y Trabajadores Asimilados No Clasificados en Otras Clasificaciones',
  85.0: 'Pintores de Edificios, de Decoración de Teatro, de Construcción Metálica, de Autos, de Pincel y de Rodillo',
  86.0: 'Obreros en la Construcción, Albañil, Carpintero, Ebanista',
  87.0: 'Operadores de Máquinas Agrícolas, Fijas y de Instalaciones Similares y Obreros de la Manipulación de Mercancías y Materi',
  88.0: 'Conductores de Medios de Transporte y Personas en Ocupaciones Afines (Excepto a Pedal y a Mano), Chofer, Taxista',
  91.0: 'Vendedores Ambulantes',
  93.0: 'Cobradores y Vendedores de los Servicios de Transporte y Afines, Cobrador de Microbús',
  94.0: 'Personal Doméstico, Limpiadores, Lavanderos, Planchadores y Afines, Conserje, Limpiabotas, Fotógrafo Ambulante, Jardiner',
  95.0: 'Mensajeros, Repartidores, Porteros y Afines, Lector de Medidores, Guardián',
  96.0: 'Recolectores de Basura',
  98.0: 'Peones de la Minería, Suministro Electricidad, Gas y Agua, la Construcción, la Industria Manufacturera y el Transporte,'},
 'V717': {0.0: 'No trabaja',
  1.0: 'Profesional, Técnico, Gerente',
  2.0: 'Eclesiástico',
  3.0: 'Ventas',
  4.0: 'Agricultor, trabajador independiente',
  5.0: 'Agricultor, empleado',
  6.0: 'Empleada del hogar',
  7.0: 'Servicios',
  8.0: 'Habilidades manuales',
  9.0: 'Sin habilidades manuales'},
 'V719': {1.0: 'Para un familiar',
  2.0: 'Para alguien más',
  3.0: 'Por cuenta propia'},
 'V721': {1.0: 'En el hogar', 2.0: 'Fuera del hogar'},
 'V729': {0.0: 'Sin educación',
  1.0: 'Primaria incompleta',
  2.0: 'Primaria completa',
  3.0: 'Secundaria incompleta',
  4.0: 'Secundaria completa',
  5.0: 'Superior',
  8.0: 'No sabe'},
 'V730': {96.0: '96+', 98.0: 'No sabe'},
 'V731': {0.0: 'No',
  1.0: 'En el año pasado',
  2.0: 'Actualmente trabajando',
  3.0: 'Tener un trabajo, pero en licencia los últimos 7 días'},
 'V732': {1.0: 'Todo el año', 2.0: 'Por temporada', 3.0: 'De vez en cuando'},
 'V739': {1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y alguien más',
  4.0: 'Esposo/compañero',
  5.0: 'Alguien más'},
 'V740': {0.0: 'Propio',
  1.0: 'Familiar',
  2.0: 'De alguien más',
  3.0: 'Alquilado',
  4.0: 'Comunitario'},
 'V741': {0.0: 'No le pagan',
  1.0: 'Solo en efectivo',
  2.0: 'Efectivo y especie',
  3.0: 'Solo en especie'},
 'V743A': {0.0: 'Nadie',
  1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y otra persona',
  4.0: 'Solo esposo/compañero',
  5.0: 'Alguien más'},
 'V743B': {0.0: 'Nadie',
  1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y alguien más',
  4.0: 'Esposo/compañero',
  5.0: 'Alguien más'},
 'V743C': {0.0: 'Nadie',
  1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y alguien más',
  4.0: 'Esposo/compañero',
  5.0: 'Alguien más'},
 'V743D': {0.0: 'Nadie',
  1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y alguien más',
  4.0: 'Esposo/compañero',
  5.0: 'Alguien más'},
 'V743E': {0.0: 'Nadie',
  1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y alguien más',
  4.0: 'Esposo/compañero',
  5.0: 'Alguien más'},
 'V743F': {1.0: 'Entrevistada',
  2.0: 'Entrevistada y esposo/compañero',
  3.0: 'Entrevistada y alguien más',
  4.0: 'Esposo/compañero',
  5.0: 'Alguien más',
  6.0: 'Otro',
  7.0: 'Esposo/compañero no tiene ganancias'},
 'V744A': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V744B': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V744C': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V744D': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},
 'V744E': {0.0: 'No', 1.0: 'Sí', 8.0: 'No sabe'},

### Answer 2
We keep the variables by using the loc function and defining that we are selecting by naming them. We then name them `rec1_1`, `rec2_1` and `rec_3`. To update the variables and value labels objects (only keep informationfor the selected columns). Then, with the function k we select only the keys that have the same name as our selected columns, what we define in a list. We name the new *value* labels objects as new_var_labels1, new_var_labels2, and new_var_labels3. And we also name the *variable* labels objects as new_value_labels1, new_value_labels2, and new_value_labels3 using the same logic from the function, but for the attribute of varNames of the var_labels previous objects.

In [9]:
rec1_1 = rec_1.loc[:, ["CASEID", "V000", "V001", "V002", "V003", "V004", "V007", "V008", "V009", "V010", "V011", "V012", "V024", "V102", "V120", "V121", "V122", "V123", "V124", "V125", "V127", "V133"]]
rec2_1 = rec_2.loc[:, ["CASEID", "V201", "V218", "V301", "V302", "V323", "V323A", "V325A", "V326", "V327", "V337", "V359", "V360", "V361", "V362", "V363", "V364", "V367", "V372", "V372A", "V375A", "V376", "V376A", "V379", "V380"]]
rec3_1 = rec_3.loc[:, ["CASEID", "V501", "V502", "V503", "V504", "V505", "V506", "V507", "V508", "V509", "V510", "V511", "V512", "V513", "V525", "V613", "V714", "V715"]]

In [10]:
keys_keep_1 = ["CASEID", "V000", "V001", "V002", "V003", "V004", "V007", "V008", "V009", "V010", "V011", "V012", "V024", "V102", "V120", "V121", "V122", "V123", "V124", "V125", "V127", "V133"]
new_value_labels1= {k: value_labels1[k] for k in keys_keep_1 if k in value_labels1}

In [11]:
keys_keep_2 = ["CASEID", "V201", "V218", "V301", "V302", "V323", "V323A", "V325A", "V326", "V327", "V337", "V359", "V360", "V361", "V362", "V363", "V364", "V367", "V372", "V372A", "V375A", "V376", "V376A", "V379", "V380"]
new_value_labels2= {k: value_labels2[k] for k in keys_keep_2 if k in value_labels2}

In [12]:
keys_keep_3 = ["CASEID", "V501", "V502", "V503", "V504", "V505", "V506", "V507", "V508", "V509", "V510", "V511", "V512", "V513", "V525", "V613", "V714", "V715"]
new_value_labels3= {k: value_labels3[k] for k in keys_keep_3 if k in value_labels3}

In [13]:
#new_val_labels1

In [14]:
new_var_labels1 = {var for var in var_labels1.varNames if var in keys_keep_1}
new_var_labels2 = {var for var in var_labels2.varNames if var in keys_keep_2}
new_var_labels3 = {var for var in var_labels3.varNames if var in keys_keep_3}

In [15]:
new_var_labels1

{'CASEID',
 'V000',
 'V001',
 'V002',
 'V003',
 'V004',
 'V007',
 'V008',
 'V009',
 'V010',
 'V011',
 'V012',
 'V024',
 'V102',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V127',
 'V133'}

#### Answer 3:
For the new column, we use the `loc` method to select a new column and give it the value 2019.
For the new key in the dictionary, we use the `update` method to set a new key with its value.

In [16]:
rec1_1.loc[:,'year'] = 2019

In [17]:
new_var_labels1.update({'year':'Year of the survey'})

#### Answer 4
We use Dataframe.merge method to merge two or multiple Dataframes. 
We use "outer" merge to combine all the rows and to complete with NaN when are no matched values in the rows.

In [18]:
endes_2019 = rec1_1.merge(rec2_1, on="CASEID", how="outer").merge(rec3_1, on="CASEID", how="outer")
endes_2019

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V508,V509,V510,V511,V512,V513,V525,V613,V714,V715
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,2008.0,1297.0,Tiene mes y año,21.0,11.0,De 10 a 14 años,17.0,2.0,Sí,11.0
1,000100201 3,PE6,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,000102801 2,PE6,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,2011.0,1344.0,Tiene mes y año,28.0,7.0,De 5 a 9 años,18.0,3.0,Sí,14.0
3,000102801 6,PE6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,1984.0,1016.0,Tiene año - imputa mes,14.0,34.0,De 30 a más años,14.0,0.0,No,6.0
4,000104801 2,PE6,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,2009.0,1320.0,Tiene mes y año,18.0,9.0,De 5 a 9 años,15.0,2.0,No,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,325406201 2,PE6,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,1985.0,1032.0,Tiene mes y año,14.0,34.0,De 30 a más años,12.0,3.0,No,5.0
38331,325406301 2,PE6,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,2002.0,1236.0,Tiene mes y año,14.0,17.0,De 15 a 19 años,12.0,3.0,No,7.0
38332,325407001 2,PE6,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,1986.0,1043.0,Tiene mes y año,13.0,33.0,De 30 a más años,12.0,4.0,No,5.0
38333,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,2008.0,1301.0,Tiene mes y año,13.0,11.0,De 10 a 14 años,13.0,2.0,No,11.0
38334,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,2013.0,1362.0,Tiene mes y año,16.0,6.0,De 5 a 9 años,15.0,2.0,No,11.0

#### Answer 5:
We made the same process to get both `var_labels` and `value_labels` objects. Start coping the object with the first group of labels, then update the new object adding the keys from the second group of labels and, finally, update the new object again, but with the keys from the third group of labels.

Those two objects were used to create new attributes for `endes_2019` using `attrs` method.

In [19]:
var_labels = new_var_labels1.copy()
var_labels.update(new_var_labels2)
var_labels.update(new_var_labels3)

In [20]:
value_labels = new_value_labels1.copy()
value_labels.update(new_value_labels2)
value_labels.update(new_value_labels3)

In [21]:
endes_2019.attrs[ 'var_labels' ] = var_labels
endes_2019.attrs[ 'value_labels' ] = value_labels

#### Answer 6:
Steps:
1. Select the columns of interest, use `describe` to get all the summary statistics and use `reset_index` to get the index with the name of statistics as a column.
2. Use `melt` method to get the column names as a variable itself.
3. Use `pivot` method to obtain new columns named as each statistic. Erase name axis for "index" and then reset the index to get a table of double entry.
4. Use `loc` to select only the desired statistics.
5. Add a new column containing the number of missing values for each variable.
6. Use `sort_values` method to sort ascending the new dataframe by number of missing rows.
7. Give a list with the new names for each column.

In [22]:
summary = endes_2019.loc[:,['V201','V613','V715','V511']].describe(include='all').reset_index()
summary = summary.melt(id_vars = ['index'], var_name = 'Variables', value_name = 'values')
summary = summary.pivot(index = 'Variables', columns = 'index', values = 'values').rename_axis( [None], axis = 1 ).reset_index()
summary = summary.loc[:,['Variables','min','max','mean','count']]
summary.loc[:,'N_missing'] = list(endes_2019.loc[:,['V201','V613','V715','V511']].isnull().sum())
summary = summary.sort_values('N_missing')
summary.columns = ['Variables', 'Min', 'Max', 'Mean', 'N_obs', 'N_missing']
summary

  Variables   Min   Max       Mean    N_obs  N_missing
0      V201   0.0  13.0   1.781946  36922.0       1413
1      V511  10.0  48.0  20.463738  25881.0       5024
2      V613   NaN   NaN        NaN  33311.0      12454
3      V715   NaN   NaN        NaN  25881.0      12454

#### Answer 7
First of all, we use the "group.by mean" function in order to get the mean of multiple columns at a time for each grup, in this case, by year and department.
After that, we use the "rename" function to rename some selected columns.

In [23]:
endes_2019.loc[:,'V613'] = endes_2019.loc[:,'V613'].replace('Respuesta no numérica', np.nan).astype(str).astype(float)
endes_2019.loc[:,'V715'] = endes_2019.loc[:,'V715'].replace('No sabe', np.nan).astype(str).astype(float)

In [24]:
mean_key_vars = endes_2019.groupby( 'V024', as_index=False )['V201' ,'V613' , 'V715', 'V511'].mean()
mean_key_vars

C:\Users\DELL\AppData\Local\Temp\ipykernel_16128\1915582610.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mean_key_vars = endes_2019.groupby( 'V024', as_index=False )['V201' ,'V613' , 'V715', 'V511'].mean()

              V024      V201      V613       V715       V511
0          Huanuco  1.989754  2.446940   8.842528  19.818632
1              Ica  1.671034  2.353429  11.825332  20.747208
2            Junin  1.836656  2.199660  10.942122  20.683761
3      La Libertad  1.704082  2.355519   9.907909  20.774678
4       Lambayeque  1.673928  2.399849  11.123396  20.953831
5             Lima  1.476121  2.235107  11.731348  21.946329
6           Loreto  2.157568  2.476703  10.109375  18.448529
7    Madre de Dios  1.972514  2.272398  10.729053  19.467449
8         Moquegua  1.626724  1.965613  12.568605  21.640046
9            Pasco  1.854436  2.526570  11.032680  20.395379
10           Piura  1.812752  2.611650  10.032480  20.451737
11            Puno  1.794307  2.024316  10.836151  20.398964
12      San Martin  1.903340  2.493333   9.621053  18.953155
13           Tacna  1.436502  2.013083  12.141403  22.065095
14          Tumbes  1.756925  2.469824  11.118095  19.409821
15         Ucayali  2.012258  2.388399  10.709355  18.985481
16        Amazonas  1.980892  2.443906   9.440580  19.266152
17          Ancash  1.771065  2.383260  10.495381  20.591581
18        Apurimac  2.003463  2.207269  10.537530  20.064982
19        Arequipa  1.539910  2.137875  12.244275  22.304394
20        Ayacucho  1.848787  2.209026  10.470772  20.340228
21       Cajamarca  1.931559  2.545923   8.708874  19.610695
22          Callao  1.567164  2.241724  11.663909  21.517241
23           Cusco  1.894415  2.100097  10.569194  20.283154
24    Huancavelica  2.083969  2.295098   9.879221  19.780769

In [25]:
mean_key_vars = mean_key_vars.rename(columns={'V201':'mean_total_children', 'V613':'mean_ideal_children', 'V715':'mean_hb_yr_educ', 'V511':'mean_first_marriage'})
mean_key_vars

,V024,mean_total_children,mean_ideal_children,mean_hb_yr_educ,mean_first_marriage
0,Huanuco,1.989754,2.446940,8.842528,19.818632
1,Ica,1.671034,2.353429,11.825332,20.747208
2,Junin,1.836656,2.199660,10.942122,20.683761
3,La Libertad,1.704082,2.355519,9.907909,20.774678
4,Lambayeque,1.673928,2.399849,11.123396,20.953831
5,Lima,1.476121,2.235107,11.731348,21.946329
6,Loreto,2.157568,2.476703,10.109375,18.448529
7,Madre de Dios,1.972514,2.272398,10.729053,19.467449
8,Moquegua,1.626724,1.965613,12.568605,21.640046
9,Pasco,1.854436,2.526570,11.032680,20.395379
10,Piura,1.812752,2.611650,10.032480,20.451737
11,Puno,1.794307,2.024316,10.836151,20.398964
12,San Martin,1.903340,2.493333,9.621053,18.953155
13,Tacna,1.436502,2.013083,12.141403,22.065095
14,Tumbes,1.756925,2.469824,11.118095,19.409821
15,Ucayali,2.012258,2.388399,10.709355,18.985481
16,Amazonas,1.980892,2.443906,9.440580,19.266152
17,Ancash,1.771065,2.383260,10.495381,20.591581
18,Apurimac,2.003463,2.207269,10.537530,20.064982
19,Arequipa,1.539910,2.137875,12.244275,22.304394
20,Ayacucho,1.848787,2.209026,10.470772,20.340228
21,Cajamarca,1.931559,2.545923,8.708874,19.610695
22,Callao,1.567164,2.241724,11.663909,21.517241
23,Cusco,1.894415,2.100097,10.569194,20.283154
24,Huancavelica,2.083969,2.295098,9.879221,19.780769

In [26]:
endes_2019.loc[:,'V613'] = endes_2019.loc[:,'V613'].replace('Respuesta no numérica', np.nan).astype(str).astype(float)
endes_2019.loc[:,'V715'] = endes_2019.loc[:,'V715'].replace('No sabe', np.nan).astype(str).astype(float)

#### Answer 8
We use "melt" function to convert a dataframe from wide format to a long format.
In this case varible "V024" is the column that we use as an id,
and the rest are the columns we unpivot. This function allow us to put
names to the columns which have the variables and values, but not for the id column. 
That's why we use the "rename" function to do it.

In [27]:
reshape_mean_key_vars = pd.melt(mean_key_vars, id_vars='V024', value_vars=['mean_total_children', 'mean_ideal_children', 'mean_hb_yr_educ', 'mean_first_marriage'],
             var_name='variables', value_name='values')
reshape_mean_key_vars

            V024            variables     values
0        Huanuco  mean_total_children   1.989754
1            Ica  mean_total_children   1.671034
2          Junin  mean_total_children   1.836656
3    La Libertad  mean_total_children   1.704082
4     Lambayeque  mean_total_children   1.673928
..           ...                  ...        ...
95      Ayacucho  mean_first_marriage  20.340228
96     Cajamarca  mean_first_marriage  19.610695
97        Callao  mean_first_marriage  21.517241
98         Cusco  mean_first_marriage  20.283154
99  Huancavelica  mean_first_marriage  19.780769

[100 rows x 3 columns]

In [28]:
reshape_mean_key_vars = reshape_mean_key_vars.rename(columns={'V024':'dpto'})
reshape_mean_key_vars

            dpto            variables     values
0        Huanuco  mean_total_children   1.989754
1            Ica  mean_total_children   1.671034
2          Junin  mean_total_children   1.836656
3    La Libertad  mean_total_children   1.704082
4     Lambayeque  mean_total_children   1.673928
..           ...                  ...        ...
95      Ayacucho  mean_first_marriage  20.340228
96     Cajamarca  mean_first_marriage  19.610695
97        Callao  mean_first_marriage  21.517241
98         Cusco  mean_first_marriage  20.283154
99  Huancavelica  mean_first_marriage  19.780769

[100 rows x 3 columns]

### Answer 9
In order to make it in one line, we group all the functions using the dot. That is, we start by renaming (rename) the columns, then getting the mean (mean) by groups  (groupbys).

In [29]:
# Answaer 7
mean_key_vars = endes_2019.groupby(["V024"], as_index=False)[["V201","V613","V715","V511"]].mean().rename(columns = {"V201":"mean_total_children","V613":"mean_ideal_children","V715":"mean_hb_yr_educ","V511":"mean_first_marriage"})
# Answer 8
reshape_mean_key_vars = pd.melt(mean_key_vars, id_vars = ["V024"], var_name = "variables", value_name = "values").rename(columns = {"V024":"dpto"})

### Answer 10
Finally, we merge reshape_mean_key_vars with endes_2019 by the left and in multiple by multiple type using the merge function.

In [31]:
final_result = endes_2019.merge(reshape_mean_key_vars.rename(columns={"dpto":"V024"}), on = ['V024'], how = "left", validate = "m:m")
final_result

,CASEID,V000,V001,V002,V003,V004,V007,V008,V009,V010,...,V510,V511,V512,V513,V525,V613,V714,V715,variables,values
0,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,Tiene mes y año,21.0,11.0,De 10 a 14 años,17.0,2.0,Sí,11.0,mean_total_children,1.980892
1,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,Tiene mes y año,21.0,11.0,De 10 a 14 años,17.0,2.0,Sí,11.0,mean_ideal_children,2.443906
2,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,Tiene mes y año,21.0,11.0,De 10 a 14 años,17.0,2.0,Sí,11.0,mean_hb_yr_educ,9.440580
3,000100201 2,PE6,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,Tiene mes y año,21.0,11.0,De 10 a 14 años,17.0,2.0,Sí,11.0,mean_first_marriage,19.266152
4,000100201 3,PE6,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mean_total_children,1.980892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153335,325407201 2,PE6,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,Tiene mes y año,13.0,11.0,De 10 a 14 años,13.0,2.0,No,11.0,mean_first_marriage,18.985481
153336,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,Tiene mes y año,16.0,6.0,De 5 a 9 años,15.0,2.0,No,11.0,mean_total_children,2.012258
153337,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,Tiene mes y año,16.0,6.0,De 5 a 9 años,15.0,2.0,No,11.0,mean_ideal_children,2.388399
153338,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,Tiene mes y año,16.0,6.0,De 5 a 9 años,15.0,2.0,No,11.0,mean_hb_yr_educ,10.709355
153339,325407401 2,PE6,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,Tiene mes y año,16.0,6.0,De 5 a 9 años,15.0,2.0,No,11.0,mean_first_marriage,18.985481