# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries

In [165]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [166]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>

In [167]:
##First, we load "pandas" and "numpy"

import pandas as pd
import numpy as np

In [168]:
##We create "even_numbers" using the method np.arange. It goes from 0 to 2000 with a step of one.

even_numbers = np.arange (0, 2001, 1)
even_numbers

array([   0,    1,    2, ..., 1998, 1999, 2000])

In [169]:
##We create "odd_numbers" using the method np.arange. It goes from 9000 to 19000 with a step of one.


odd_numbers = np.arange (9000, 19001, 1)
odd_numbers

array([ 9000,  9001,  9002, ..., 18998, 18999, 19000])

In [170]:
##Finally, with the funtion zip we create "result" that have both even_numbers and odd_numbers. We print it as a list. 

result = zip (even_numbers, odd_numbers)
print(list(result))

[(0, 9000), (1, 9001), (2, 9002), (3, 9003), (4, 9004), (5, 9005), (6, 9006), (7, 9007), (8, 9008), (9, 9009), (10, 9010), (11, 9011), (12, 9012), (13, 9013), (14, 9014), (15, 9015), (16, 9016), (17, 9017), (18, 9018), (19, 9019), (20, 9020), (21, 9021), (22, 9022), (23, 9023), (24, 9024), (25, 9025), (26, 9026), (27, 9027), (28, 9028), (29, 9029), (30, 9030), (31, 9031), (32, 9032), (33, 9033), (34, 9034), (35, 9035), (36, 9036), (37, 9037), (38, 9038), (39, 9039), (40, 9040), (41, 9041), (42, 9042), (43, 9043), (44, 9044), (45, 9045), (46, 9046), (47, 9047), (48, 9048), (49, 9049), (50, 9050), (51, 9051), (52, 9052), (53, 9053), (54, 9054), (55, 9055), (56, 9056), (57, 9057), (58, 9058), (59, 9059), (60, 9060), (61, 9061), (62, 9062), (63, 9063), (64, 9064), (65, 9065), (66, 9066), (67, 9067), (68, 9068), (69, 9069), (70, 9070), (71, 9071), (72, 9072), (73, 9073), (74, 9074), (75, 9075), (76, 9076), (77, 9077), (78, 9078), (79, 9079), (80, 9080), (81, 9081), (82, 9082), (83, 9083), (84, 9084), (85, 9085), (86, 9086), (87, 9087), (88, 9088), (89, 9089), (90, 9090), (91, 9091), (92, 9092), (93, 9093), (94, 9094), (95, 9095), (96, 9096), (97, 9097), (98, 9098), (99, 9099), (100, 9100), (101, 9101), (102, 9102), (103, 9103), (104, 9104), (105, 9105), (106, 9106), (107, 9107), (108, 9108), (109, 9109), (110, 9110), (111, 9111), (112, 9112), (113, 9113), (114, 9114), (115, 9115), (116, 9116), (117, 9117), (118, 9118), (119, 9119), (120, 9120), (121, 9121), (122, 9122), (123, 9123), (124, 9124), (125, 9125), (126, 9126), (127, 9127), (128, 9128), (129, 9129), (130, 9130), (131, 9131), (132, 9132), (133, 9133), (134, 9134), (135, 9135), (136, 9136), (137, 9137), (138, 9138), (139, 9139), (140, 9140), (141, 9141), (142, 9142), (143, 9143), (144, 9144), (145, 9145), (146, 9146), (147, 9147), (148, 9148), (149, 9149), (150, 9150), (151, 9151), (152, 9152), (153, 9153), (154, 9154), (155, 9155), (156, 9156), (157, 9157), (158, 9158), (159, 9159), (160, 9160), (161, 9161), (162, 9162), (163, 9163), (164, 9164), (165, 9165), (166, 9166), (167, 9167), (168, 9168), (169, 9169), (170, 9170), (171, 9171), (172, 9172), (173, 9173), (174, 9174), (175, 9175), (176, 9176), (177, 9177), (178, 9178), (179, 9179), (180, 9180), (181, 9181), (182, 9182), (183, 9183), (184, 9184), (185, 9185), (186, 9186), (187, 9187), (188, 9188), (189, 9189), (190, 9190), (191, 9191), (192, 9192), (193, 9193), (194, 9194), (195, 9195), (196, 9196), (197, 9197), (198, 9198), (199, 9199), (200, 9200), (201, 9201), (202, 9202), (203, 9203), (204, 9204), (205, 9205), (206, 9206), (207, 9207), (208, 9208), (209, 9209), (210, 9210), (211, 9211), (212, 9212), (213, 9213), (214, 9214), (215, 9215), (216, 9216), (217, 9217), (218, 9218), (219, 9219), (220, 9220), (221, 9221), (222, 9222), (223, 9223), (224, 9224), (225, 9225), (226, 9226), (227, 9227), (228, 9228), (229, 9229), (230, 9230), (231, 9231), (232, 9232), (233, 9233), (234, 9234), (235, 9235), (236, 9236), (237, 9237), (238, 9238), (239, 9239), (240, 9240), (241, 9241), (242, 9242), (243, 9243), (244, 9244), (245, 9245), (246, 9246), (247, 9247), (248, 9248), (249, 9249), (250, 9250), (251, 9251), (252, 9252), (253, 9253), (254, 9254), (255, 9255), (256, 9256), (257, 9257), (258, 9258), (259, 9259), (260, 9260), (261, 9261), (262, 9262), (263, 9263), (264, 9264), (265, 9265), (266, 9266), (267, 9267), (268, 9268), (269, 9269), (270, 9270), (271, 9271), (272, 9272), (273, 9273), (274, 9274), (275, 9275), (276, 9276), (277, 9277), (278, 9278), (279, 9279), (280, 9280), (281, 9281), (282, 9282), (283, 9283), (284, 9284), (285, 9285), (286, 9286), (287, 9287), (288, 9288), (289, 9289), (290, 9290), (291, 9291), (292, 9292), (293, 9293), (294, 9294), (295, 9295), (296, 9296), (297, 9297), (298, 9298), (299, 9299), (300, 9300), (301, 9301), (302, 9302), (303, 9303), (304, 9304), (305, 9305), (306, 9306), (307, 9307), (308, 9308), (309, 9309), (310, 9310), (311, 9311), (312, 9312), (313, 9313), (314, 9314), (315, 9315), (316, 9316), (317, 9317), (318, 9318), (319, 9319), (320, 9320), (321, 9321), (322, 9322), (323, 9323), (324, 9324), (325, 9325), (326, 9326), (327, 9327), (328, 9328), (329, 9329), (330, 9330), (331, 9331), (332, 9332), (333, 9333), (334, 9334), (335, 9335), (336, 9336), (337, 9337), (338, 9338), (339, 9339), (340, 9340), (341, 9341), (342, 9342), (343, 9343), (344, 9344), (345, 9345), (346, 9346), (347, 9347), (348, 9348), (349, 9349), (350, 9350), (351, 9351), (352, 9352), (353, 9353), (354, 9354), (355, 9355), (356, 9356), (357, 9357), (358, 9358), (359, 9359), (360, 9360), (361, 9361), (362, 9362), (363, 9363), (364, 9364), (365, 9365), (366, 9366), (367, 9367), (368, 9368), (369, 9369), (370, 9370), (371, 9371), (372, 9372), (373, 9373), (374, 9374), (375, 9375), (376, 9376), (377, 9377), (378, 9378), (379, 9379), (380, 9380), (381, 9381), (382, 9382), (383, 9383), (384, 9384), (385, 9385), (386, 9386), (387, 9387), (388, 9388), (389, 9389), (390, 9390), (391, 9391), (392, 9392), (393, 9393), (394, 9394), (395, 9395), (396, 9396), (397, 9397), (398, 9398), (399, 9399), (400, 9400), (401, 9401), (402, 9402), (403, 9403), (404, 9404), (405, 9405), (406, 9406), (407, 9407), (408, 9408), (409, 9409), (410, 9410), (411, 9411), (412, 9412), (413, 9413), (414, 9414), (415, 9415), (416, 9416), (417, 9417), (418, 9418), (419, 9419), (420, 9420), (421, 9421), (422, 9422), (423, 9423), (424, 9424), (425, 9425), (426, 9426), (427, 9427), (428, 9428), (429, 9429), (430, 9430), (431, 9431), (432, 9432), (433, 9433), (434, 9434), (435, 9435), (436, 9436), (437, 9437), (438, 9438), (439, 9439), (440, 9440), (441, 9441), (442, 9442), (443, 9443), (444, 9444), (445, 9445), (446, 9446), (447, 9447), (448, 9448), (449, 9449), (450, 9450), (451, 9451), (452, 9452), (453, 9453), (454, 9454), (455, 9455), (456, 9456), (457, 9457), (458, 9458), (459, 9459), (460, 9460), (461, 9461), (462, 9462), (463, 9463), (464, 9464), (465, 9465), (466, 9466), (467, 9467), (468, 9468), (469, 9469), (470, 9470), (471, 9471), (472, 9472), (473, 9473), (474, 9474), (475, 9475), (476, 9476), (477, 9477), (478, 9478), (479, 9479), (480, 9480), (481, 9481), (482, 9482), (483, 9483), (484, 9484), (485, 9485), (486, 9486), (487, 9487), (488, 9488), (489, 9489), (490, 9490), (491, 9491), (492, 9492), (493, 9493), (494, 9494), (495, 9495), (496, 9496), (497, 9497), (498, 9498), (499, 9499), (500, 9500), (501, 9501), (502, 9502), (503, 9503), (504, 9504), (505, 9505), (506, 9506), (507, 9507), (508, 9508), (509, 9509), (510, 9510), (511, 9511), (512, 9512), (513, 9513), (514, 9514), (515, 9515), (516, 9516), (517, 9517), (518, 9518), (519, 9519), (520, 9520), (521, 9521), (522, 9522), (523, 9523), (524, 9524), (525, 9525), (526, 9526), (527, 9527), (528, 9528), (529, 9529), (530, 9530), (531, 9531), (532, 9532), (533, 9533), (534, 9534), (535, 9535), (536, 9536), (537, 9537), (538, 9538), (539, 9539), (540, 9540), (541, 9541), (542, 9542), (543, 9543), (544, 9544), (545, 9545), (546, 9546), (547, 9547), (548, 9548), (549, 9549), (550, 9550), (551, 9551), (552, 9552), (553, 9553), (554, 9554), (555, 9555), (556, 9556), (557, 9557), (558, 9558), (559, 9559), (560, 9560), (561, 9561), (562, 9562), (563, 9563), (564, 9564), (565, 9565), (566, 9566), (567, 9567), (568, 9568), (569, 9569), (570, 9570), (571, 9571), (572, 9572), (573, 9573), (574, 9574), (575, 9575), (576, 9576), (577, 9577), (578, 9578), (579, 9579), (580, 9580), (581, 9581), (582, 9582), (583, 9583), (584, 9584), (585, 9585), (586, 9586), (587, 9587), (588, 9588), (589, 9589), (590, 9590), (591, 9591), (592, 9592), (593, 9593), (594, 9594), (595, 9595), (596, 9596), (597, 9597), (598, 9598), (599, 9599), (600, 9600), (601, 9601), (602, 9602), (603, 9603), (604, 9604), (605, 9605), (606, 9606), (607, 9607), (608, 9608), (609, 9609), (610, 9610), (611, 9611), (612, 9612), (613, 9613), (614, 9614), (615, 9615), (616, 9616), (617, 9617), (618, 9618), (619, 9619), (620, 9620), (621, 9621), (622, 9622), (623, 9623), (624, 9624), (625, 9625), (626, 9626), (627, 9627), (628, 9628), (629, 9629), (630, 9630), (631, 9631), (632, 9632), (633, 9633), (634, 9634), (635, 9635), (636, 9636), (637, 9637), (638, 9638), (639, 9639), (640, 9640), (641, 9641), (642, 9642), (643, 9643), (644, 9644), (645, 9645), (646, 9646), (647, 9647), (648, 9648), (649, 9649), (650, 9650), (651, 9651), (652, 9652), (653, 9653), (654, 9654), (655, 9655), (656, 9656), (657, 9657), (658, 9658), (659, 9659), (660, 9660), (661, 9661), (662, 9662), (663, 9663), (664, 9664), (665, 9665), (666, 9666), (667, 9667), (668, 9668), (669, 9669), (670, 9670), (671, 9671), (672, 9672), (673, 9673), (674, 9674), (675, 9675), (676, 9676), (677, 9677), (678, 9678), (679, 9679), (680, 9680), (681, 9681), (682, 9682), (683, 9683), (684, 9684), (685, 9685), (686, 9686), (687, 9687), (688, 9688), (689, 9689), (690, 9690), (691, 9691), (692, 9692), (693, 9693), (694, 9694), (695, 9695), (696, 9696), (697, 9697), (698, 9698), (699, 9699), (700, 9700), (701, 9701), (702, 9702), (703, 9703), (704, 9704), (705, 9705), (706, 9706), (707, 9707), (708, 9708), (709, 9709), (710, 9710), (711, 9711), (712, 9712), (713, 9713), (714, 9714), (715, 9715), (716, 9716), (717, 9717), (718, 9718), (719, 9719), (720, 9720), (721, 9721), (722, 9722), (723, 9723), (724, 9724), (725, 9725), (726, 9726), (727, 9727), (728, 9728), (729, 9729), (730, 9730), (731, 9731), (732, 9732), (733, 9733), (734, 9734), (735, 9735), (736, 9736), (737, 9737), (738, 9738), (739, 9739), (740, 9740), (741, 9741), (742, 9742), (743, 9743), (744, 9744), (745, 9745), (746, 9746), (747, 9747), (748, 9748), (749, 9749), (750, 9750), (751, 9751), (752, 9752), (753, 9753), (754, 9754), (755, 9755), (756, 9756), (757, 9757), (758, 9758), (759, 9759), (760, 9760), (761, 9761), (762, 9762), (763, 9763), (764, 9764), (765, 9765), (766, 9766), (767, 9767), (768, 9768), (769, 9769), (770, 9770), (771, 9771), (772, 9772), (773, 9773), (774, 9774), (775, 9775), (776, 9776), (777, 9777), (778, 9778), (779, 9779), (780, 9780), (781, 9781), (782, 9782), (783, 9783), (784, 9784), (785, 9785), (786, 9786), (787, 9787), (788, 9788), (789, 9789), (790, 9790), (791, 9791), (792, 9792), (793, 9793), (794, 9794), (795, 9795), (796, 9796), (797, 9797), (798, 9798), (799, 9799), (800, 9800), (801, 9801), (802, 9802), (803, 9803), (804, 9804), (805, 9805), (806, 9806), (807, 9807), (808, 9808), (809, 9809), (810, 9810), (811, 9811), (812, 9812), (813, 9813), (814, 9814), (815, 9815), (816, 9816), (817, 9817), (818, 9818), (819, 9819), (820, 9820), (821, 9821), (822, 9822), (823, 9823), (824, 9824), (825, 9825), (826, 9826), (827, 9827), (828, 9828), (829, 9829), (830, 9830), (831, 9831), (832, 9832), (833, 9833), (834, 9834), (835, 9835), (836, 9836), (837, 9837), (838, 9838), (839, 9839), (840, 9840), (841, 9841), (842, 9842), (843, 9843), (844, 9844), (845, 9845), (846, 9846), (847, 9847), (848, 9848), (849, 9849), (850, 9850), (851, 9851), (852, 9852), (853, 9853), (854, 9854), (855, 9855), (856, 9856), (857, 9857), (858, 9858), (859, 9859), (860, 9860), (861, 9861), (862, 9862), (863, 9863), (864, 9864), (865, 9865), (866, 9866), (867, 9867), (868, 9868), (869, 9869), (870, 9870), (871, 9871), (872, 9872), (873, 9873), (874, 9874), (875, 9875), (876, 9876), (877, 9877), (878, 9878), (879, 9879), (880, 9880), (881, 9881), (882, 9882), (883, 9883), (884, 9884), (885, 9885), (886, 9886), (887, 9887), (888, 9888), (889, 9889), (890, 9890), (891, 9891), (892, 9892), (893, 9893), (894, 9894), (895, 9895), (896, 9896), (897, 9897), (898, 9898), (899, 9899), (900, 9900), (901, 9901), (902, 9902), (903, 9903), (904, 9904), (905, 9905), (906, 9906), (907, 9907), (908, 9908), (909, 9909), (910, 9910), (911, 9911), (912, 9912), (913, 9913), (914, 9914), (915, 9915), (916, 9916), (917, 9917), (918, 9918), (919, 9919), (920, 9920), (921, 9921), (922, 9922), (923, 9923), (924, 9924), (925, 9925), (926, 9926), (927, 9927), (928, 9928), (929, 9929), (930, 9930), (931, 9931), (932, 9932), (933, 9933), (934, 9934), (935, 9935), (936, 9936), (937, 9937), (938, 9938), (939, 9939), (940, 9940), (941, 9941), (942, 9942), (943, 9943), (944, 9944), (945, 9945), (946, 9946), (947, 9947), (948, 9948), (949, 9949), (950, 9950), (951, 9951), (952, 9952), (953, 9953), (954, 9954), (955, 9955), (956, 9956), (957, 9957), (958, 9958), (959, 9959), (960, 9960), (961, 9961), (962, 9962), (963, 9963), (964, 9964), (965, 9965), (966, 9966), (967, 9967), (968, 9968), (969, 9969), (970, 9970), (971, 9971), (972, 9972), (973, 9973), (974, 9974), (975, 9975), (976, 9976), (977, 9977), (978, 9978), (979, 9979), (980, 9980), (981, 9981), (982, 9982), (983, 9983), (984, 9984), (985, 9985), (986, 9986), (987, 9987), (988, 9988), (989, 9989), (990, 9990), (991, 9991), (992, 9992), (993, 9993), (994, 9994), (995, 9995), (996, 9996), (997, 9997), (998, 9998), (999, 9999), (1000, 10000), (1001, 10001), (1002, 10002), (1003, 10003), (1004, 10004), (1005, 10005), (1006, 10006), (1007, 10007), (1008, 10008), (1009, 10009), (1010, 10010), (1011, 10011), (1012, 10012), (1013, 10013), (1014, 10014), (1015, 10015), (1016, 10016), (1017, 10017), (1018, 10018), (1019, 10019), (1020, 10020), (1021, 10021), (1022, 10022), (1023, 10023), (1024, 10024), (1025, 10025), (1026, 10026), (1027, 10027), (1028, 10028), (1029, 10029), (1030, 10030), (1031, 10031), (1032, 10032), (1033, 10033), (1034, 10034), (1035, 10035), (1036, 10036), (1037, 10037), (1038, 10038), (1039, 10039), (1040, 10040), (1041, 10041), (1042, 10042), (1043, 10043), (1044, 10044), (1045, 10045), (1046, 10046), (1047, 10047), (1048, 10048), (1049, 10049), (1050, 10050), (1051, 10051), (1052, 10052), (1053, 10053), (1054, 10054), (1055, 10055), (1056, 10056), (1057, 10057), (1058, 10058), (1059, 10059), (1060, 10060), (1061, 10061), (1062, 10062), (1063, 10063), (1064, 10064), (1065, 10065), (1066, 10066), (1067, 10067), (1068, 10068), (1069, 10069), (1070, 10070), (1071, 10071), (1072, 10072), (1073, 10073), (1074, 10074), (1075, 10075), (1076, 10076), (1077, 10077), (1078, 10078), (1079, 10079), (1080, 10080), (1081, 10081), (1082, 10082), (1083, 10083), (1084, 10084), (1085, 10085), (1086, 10086), (1087, 10087), (1088, 10088), (1089, 10089), (1090, 10090), (1091, 10091), (1092, 10092), (1093, 10093), (1094, 10094), (1095, 10095), (1096, 10096), (1097, 10097), (1098, 10098), (1099, 10099), (1100, 10100), (1101, 10101), (1102, 10102), (1103, 10103), (1104, 10104), (1105, 10105), (1106, 10106), (1107, 10107), (1108, 10108), (1109, 10109), (1110, 10110), (1111, 10111), (1112, 10112), (1113, 10113), (1114, 10114), (1115, 10115), (1116, 10116), (1117, 10117), (1118, 10118), (1119, 10119), (1120, 10120), (1121, 10121), (1122, 10122), (1123, 10123), (1124, 10124), (1125, 10125), (1126, 10126), (1127, 10127), (1128, 10128), (1129, 10129), (1130, 10130), (1131, 10131), (1132, 10132), (1133, 10133), (1134, 10134), (1135, 10135), (1136, 10136), (1137, 10137), (1138, 10138), (1139, 10139), (1140, 10140), (1141, 10141), (1142, 10142), (1143, 10143), (1144, 10144), (1145, 10145), (1146, 10146), (1147, 10147), (1148, 10148), (1149, 10149), (1150, 10150), (1151, 10151), (1152, 10152), (1153, 10153), (1154, 10154), (1155, 10155), (1156, 10156), (1157, 10157), (1158, 10158), (1159, 10159), (1160, 10160), (1161, 10161), (1162, 10162), (1163, 10163), (1164, 10164), (1165, 10165), (1166, 10166), (1167, 10167), (1168, 10168), (1169, 10169), (1170, 10170), (1171, 10171), (1172, 10172), (1173, 10173), (1174, 10174), (1175, 10175), (1176, 10176), (1177, 10177), (1178, 10178), (1179, 10179), (1180, 10180), (1181, 10181), (1182, 10182), (1183, 10183), (1184, 10184), (1185, 10185), (1186, 10186), (1187, 10187), (1188, 10188), (1189, 10189), (1190, 10190), (1191, 10191), (1192, 10192), (1193, 10193), (1194, 10194), (1195, 10195), (1196, 10196), (1197, 10197), (1198, 10198), (1199, 10199), (1200, 10200), (1201, 10201), (1202, 10202), (1203, 10203), (1204, 10204), (1205, 10205), (1206, 10206), (1207, 10207), (1208, 10208), (1209, 10209), (1210, 10210), (1211, 10211), (1212, 10212), (1213, 10213), (1214, 10214), (1215, 10215), (1216, 10216), (1217, 10217), (1218, 10218), (1219, 10219), (1220, 10220), (1221, 10221), (1222, 10222), (1223, 10223), (1224, 10224), (1225, 10225), (1226, 10226), (1227, 10227), (1228, 10228), (1229, 10229), (1230, 10230), (1231, 10231), (1232, 10232), (1233, 10233), (1234, 10234), (1235, 10235), (1236, 10236), (1237, 10237), (1238, 10238), (1239, 10239), (1240, 10240), (1241, 10241), (1242, 10242), (1243, 10243), (1244, 10244), (1245, 10245), (1246, 10246), (1247, 10247), (1248, 10248), (1249, 10249), (1250, 10250), (1251, 10251), (1252, 10252), (1253, 10253), (1254, 10254), (1255, 10255), (1256, 10256), (1257, 10257), (1258, 10258), (1259, 10259), (1260, 10260), (1261, 10261), (1262, 10262), (1263, 10263), (1264, 10264), (1265, 10265), (1266, 10266), (1267, 10267), (1268, 10268), (1269, 10269), (1270, 10270), (1271, 10271), (1272, 10272), (1273, 10273), (1274, 10274), (1275, 10275), (1276, 10276), (1277, 10277), (1278, 10278), (1279, 10279), (1280, 10280), (1281, 10281), (1282, 10282), (1283, 10283), (1284, 10284), (1285, 10285), (1286, 10286), (1287, 10287), (1288, 10288), (1289, 10289), (1290, 10290), (1291, 10291), (1292, 10292), (1293, 10293), (1294, 10294), (1295, 10295), (1296, 10296), (1297, 10297), (1298, 10298), (1299, 10299), (1300, 10300), (1301, 10301), (1302, 10302), (1303, 10303), (1304, 10304), (1305, 10305), (1306, 10306), (1307, 10307), (1308, 10308), (1309, 10309), (1310, 10310), (1311, 10311), (1312, 10312), (1313, 10313), (1314, 10314), (1315, 10315), (1316, 10316), (1317, 10317), (1318, 10318), (1319, 10319), (1320, 10320), (1321, 10321), (1322, 10322), (1323, 10323), (1324, 10324), (1325, 10325), (1326, 10326), (1327, 10327), (1328, 10328), (1329, 10329), (1330, 10330), (1331, 10331), (1332, 10332), (1333, 10333), (1334, 10334), (1335, 10335), (1336, 10336), (1337, 10337), (1338, 10338), (1339, 10339), (1340, 10340), (1341, 10341), (1342, 10342), (1343, 10343), (1344, 10344), (1345, 10345), (1346, 10346), (1347, 10347), (1348, 10348), (1349, 10349), (1350, 10350), (1351, 10351), (1352, 10352), (1353, 10353), (1354, 10354), (1355, 10355), (1356, 10356), (1357, 10357), (1358, 10358), (1359, 10359), (1360, 10360), (1361, 10361), (1362, 10362), (1363, 10363), (1364, 10364), (1365, 10365), (1366, 10366), (1367, 10367), (1368, 10368), (1369, 10369), (1370, 10370), (1371, 10371), (1372, 10372), (1373, 10373), (1374, 10374), (1375, 10375), (1376, 10376), (1377, 10377), (1378, 10378), (1379, 10379), (1380, 10380), (1381, 10381), (1382, 10382), (1383, 10383), (1384, 10384), (1385, 10385), (1386, 10386), (1387, 10387), (1388, 10388), (1389, 10389), (1390, 10390), (1391, 10391), (1392, 10392), (1393, 10393), (1394, 10394), (1395, 10395), (1396, 10396), (1397, 10397), (1398, 10398), (1399, 10399), (1400, 10400), (1401, 10401), (1402, 10402), (1403, 10403), (1404, 10404), (1405, 10405), (1406, 10406), (1407, 10407), (1408, 10408), (1409, 10409), (1410, 10410), (1411, 10411), (1412, 10412), (1413, 10413), (1414, 10414), (1415, 10415), (1416, 10416), (1417, 10417), (1418, 10418), (1419, 10419), (1420, 10420), (1421, 10421), (1422, 10422), (1423, 10423), (1424, 10424), (1425, 10425), (1426, 10426), (1427, 10427), (1428, 10428), (1429, 10429), (1430, 10430), (1431, 10431), (1432, 10432), (1433, 10433), (1434, 10434), (1435, 10435), (1436, 10436), (1437, 10437), (1438, 10438), (1439, 10439), (1440, 10440), (1441, 10441), (1442, 10442), (1443, 10443), (1444, 10444), (1445, 10445), (1446, 10446), (1447, 10447), (1448, 10448), (1449, 10449), (1450, 10450), (1451, 10451), (1452, 10452), (1453, 10453), (1454, 10454), (1455, 10455), (1456, 10456), (1457, 10457), (1458, 10458), (1459, 10459), (1460, 10460), (1461, 10461), (1462, 10462), (1463, 10463), (1464, 10464), (1465, 10465), (1466, 10466), (1467, 10467), (1468, 10468), (1469, 10469), (1470, 10470), (1471, 10471), (1472, 10472), (1473, 10473),

2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>

In [171]:
##With the funtion get we can take specific elements from a dictionary. We create z that gets the brand of the car.

z = car.get("brand")
print (z)

Ford

3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>

In [172]:
##If we want the values of a dictionary we can use the funtion values. We print it, so the output 
##are the values of car (dictonary)

print(car.values())

dict_values(['Ford', 'Mustang', 1964])

4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [173]:
##We call the specific values from the dictionary hr_sleep with both outer and inner keys
##then we use the funtion "max" to obtain the maximum value of that group

print(max(hr_sleep["january"]["friday"]))

2

5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [93]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [94]:
hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [95]:
#From lists to dictionary. Assign keys and values
keys = week1 
values = values2

In [96]:
#check that they are the same length
len(keys)

2

In [97]:
len(values)

2

In [98]:
# Return a dictionary
march = dict( zip( keys , values ) )
march

{'monday': [2, 3, 4], 'sunday': 8}

In [99]:
#Add march key to the hr_sleep dictionary
hr_sleep["March"] = march
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'March': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.2 Numpy

In [100]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>

In [101]:
#We see that the array np1 is composed of values from 200 to 749 incremented by 1
print(np1)

[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325
 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379
 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451
 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469
 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487
 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505
 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523
 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541
 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559
 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577
 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595
 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613
 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631
 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649
 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667
 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685
 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703
 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721
 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739
 740 741 742 743 744 745 746 747 748 749]

In [102]:
#We filter even numbers: numbers that have a remainder of 0 when divided by 2. 
np1 [np1%2 == 0] = 100

In [103]:
#We print the array again and see that all even number have been replaced with 100.
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 100 447 100 449 100 451
 100 453 100 455 100 457 100 459 100 461 100 463 100 465 100 467 100 469
 100 471 100 473 100 475 100 477 100 479 100 481 100 483 100 485 100 487
 100 489 100 491 100 493 100 495 100 497 100 499 100 501 100 503 100 505
 100 507 100 509 100 511 100 513 100 515 100 517 100 519 100 521 100 523
 100 525 100 527 100 529 100 531 100 533 100 535 100 537 100 539 100 541
 100 543 100 545 100 547 100 549 100 551 100 553 100 555 100 557 100 559
 100 561 100 563 100 565 100 567 100 569 100 571 100 573 100 575 100 577
 100 579 100 581 100 583 100 585 100 587 100 589 100 591 100 593 100 595
 100 597 100 599 100 601 100 603 100 605 100 607 100 609 100 611 100 613
 100 615 100 617 100 619 100 621 100 623 100 625 100 627 100 629 100 631
 100 633 100 635 100 637 100 639 100 641 100 643 100 645 100 647 100 649
 100 651 100 653 100 655 100 657 100 659 100 661 100 663 100 665 100 667
 100 669 100 671 100 673 100 675 100 677 100 679 100 681 100 683 100 685
 100 687 100 689 100 691 100 693 100 695 100 697 100 699 100 701 100 703
 100 705 100 707 100 709 100 711 100 713 100 715 100 717 100 719 100 721
 100 723 100 725 100 727 100 729 100 731 100 733 100 735 100 737 100 739
 100 741 100 743 100 745 100 747 100 749]

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [104]:
# Create a 1D NumPy array with values from 0 to 8 incremented by 1:
array = np.arange( 0, 9, 1 ) 
print(array)

[0 1 2 3 4 5 6 7 8]

In [105]:
#Convert the 1-D array with 9 elements into a 3x3 matrix using the n.p reshape method
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

FORM 1

In [106]:
# 1D array Z
Z = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] )
print(Z)

[ 1  2  3  4  5  6  7  8  9 10]

In [52]:
# Create each individual vector using np.arrange
a = np.arange ( 1, 5)
print(a)
b = np.arange( 2, 6)
print(b) 
c = np.arange( 3, 7)
print(c)
d = np.arange( 4, 8)
print(d)
e = np.arange( 5, 9)
print(e)
f = np.arange( 6, 10)
print(f)
g = np.arange( 7, 11)
print(g)

[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]
[5 6 7 8]
[6 7 8 9]
[ 7  8  9 10]

In [71]:
#Generating an array R using np.concatenate to join the individual vectors into one.
R = np.concatenate((a, b, c, d, e, f, g), axis=0) 
print(R)

[ 1  2  3  4  2  3  4  5  3  4  5  6  4  5  6  7  5  6  7  8  6  7  8  9
  7  8  9 10]

FORM 2

In [73]:
z= np.arange(1,11) #We create the array Z
R = np.concatenate(([z[0:4]], [z[1:5]], [z[2:6]], [z[3:7]],[z[4:8]],[z[5:9]],[z[6:10]])) #We concatenate the array by selecting the indicated values 
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [109]:
np.random.random( (3,3,3) )  #It's a funtion that returns an array with 3 sub arrays of random floats of shape size (3x3). 
#The first sub argument is to create the number of subarrays, the second one to rows and finally, the third one is to the columns.

array([[[0.24814784, 0.4394413 , 0.46425967],
        [0.66422865, 0.20511917, 0.66136323],
        [0.75677067, 0.3314973 , 0.65508102]],

       [[0.78037258, 0.12913994, 0.25095822],
        [0.5479428 , 0.56791197, 0.96897832],
        [0.58595676, 0.35508587, 0.96160249]],

       [[0.94507955, 0.98522773, 0.3324286 ],
        [0.69883843, 0.9943248 , 0.91307325],
        [0.92912548, 0.24798511, 0.93928786]]])

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

In principle, np.nan are not numbers, but are undefined values that are substitutes for the empty spaces of an array, in this case, since we are working with numpys. So, it does not make much mathematical sense to compare two undefined values.

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [110]:
mean =  round( np.mean(np2) ) #we use the function np.mean to calculate the mean of the array. Then we round the number. 
sd = round( np.sqrt ( np.var (np2) ) ) #we use the function np.var to calculate the var of the array. Then then we calculate the square root of that number and thus obtain the sd.

In [111]:
 print( f'The mean is {mean} and its standard deviation is {sd}') #we print

The mean is 50 and its standard deviation is 4

## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

In [2]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [3]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>

In [4]:
import numpy as np
greene

,id,YEAR,COST,Q,PL,SL,PK,SK,PF,SF
0,1,1970,0.2130,8.0,6869.47,0.3291,64.945,0.4197,18.000,0.2512
1,4,1970,3.0427,869.0,8372.96,0.1030,68.227,0.2913,21.067,0.6057
2,5,1970,9.4059,1412.0,7960.90,0.0891,40.692,0.1567,41.530,0.7542
3,14,1970,0.7606,65.0,8971.89,0.2802,41.243,0.1282,28.539,0.5916
4,15,1970,2.2587,295.0,8218.40,0.1772,71.940,0.1623,39.200,0.6606
...,...,...,...,...,...,...,...,...,...,...
153,214,1970,6.8293,946.6,10642.16,0.0883,43.600,0.1914,51.463,0.7203
154,215,1970,3.7605,377.0,7432.24,0.2117,74.120,0.2274,33.436,0.5609
155,216,1970,3.9822,391.0,5826.04,0.1926,78.288,0.0924,44.633,0.7151
156,217,1970,30.1880,5317.0,9586.63,0.0845,78.008,0.2009,41.840,0.7147
157,218,1970,67.8562,15220.0,6986.09,0.1451,74.025,0.2596,25.662,0.5945

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [5]:
#First, we construct the variables 
lnCT =np.log(ct).reshape(-1,1)

x0 = np.ones( len(greene) )  #we create a vector of 1's. 
x1=np.log(q)
x2= (1/2)*np.log(np.sqrt(q))
x3=np.log(q)*np.log(p1)
x4=np.log(q)*np.log(p2)
x5=np.log(q)*np.log(p3)
x6=np.log(p1)
x7=np.log(p2)
x8=np.log(p3)
x9=0.5*np.log(p1)**(2)
x10=0.5*np.log(p2)**(2)
x11=0.5*np.log(p3)**(2)
x12=0.5*np.log(p1)*np.log(p2)
x13=0.5*np.log(p1)*np.log(p3)
x14=0.5*np.log(p2)*np.log(p3)

In [6]:
#Create the matrix X
X = np.hstack(( x0.reshape(-1, 1 ) , x1.reshape(-1, 1 ), x2.reshape(-1, 1 ), x3.reshape(-1, 1 ), x4.reshape(-1, 1 )
              , x5.reshape(-1, 1 ), x6.reshape(-1, 1 ), x7.reshape(-1, 1 ), x8.reshape(-1, 1 ), x9.reshape(-1, 1 )
              , x10.reshape(-1, 1 ), x11.reshape(-1, 1 ), x12.reshape(-1, 1 ), x13.reshape(-1, 1 ), x14.reshape(-1, 1 )))
X.shape

(158, 15)

In [8]:
#We create the matrix of restrictions L*beta = r
L_1 = np.array([0,0,0,0,0,0,1,1,1,0,0,0,0,0,0])
L_2 = np.array([0,0,0,1,1,1,0,0,0,0,0,0,0,0,0])
L_3 = np.array([0,0,0,0,0,0,0,0,0,1,0,0,1,1,0])
L_4 = np.array([0,0,0,0,0,0,0,0,0,0,1,0,0,0,1])
L_5 = np.array([0,0,0,0,0,0,0,0,0,0,0,1,0,0,0])
L_6 = np.array([0,0,0,0,0,0,0,0,0,0,0,0,1,0,0])
L_7 = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1])
L_8 = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,1,0])

L = np.vstack(( L_1, L_2, L_3, L_4, L_5, L_6, L_7, L_8))
L.shape
L

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [13]:
r = np.array([1,0,0,0,0,0,0,0]).reshape(-1, 1 )
r.shape
lnCT.shape

(158, 1)

We calculate the following according to this [`page`](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).

$$
\widehat{\beta }^{\left( RLS\right) } = \widehat{\beta }^{\left( OLS\right) } - \left[
 X^{T}X\right] ^{-1}L^{T}\left( L\left(
X^{T}X\right) ^{-1}L^{T}\right) ^{-1}\left( L\widehat{\beta }^{\left( OLS\right) }-r\right) 
$$

In [14]:
#First, we calculate the beta OLS
beta_ols = np.linalg.inv(X.T @ X) @ X.T @ lnCT
beta_ols

array([[-1.81364785e+01],
       [-7.75794873e+02],
       [ 3.09174577e+03],
       [ 3.03500392e-01],
       [ 8.39207720e-02],
       [ 9.24993121e-02],
       [ 7.60494052e+00],
       [-5.91269457e+00],
       [ 2.27111177e+00],
       [-1.12847196e+00],
       [-1.98222478e-01],
       [ 2.43326855e-01],
       [ 1.26826593e+00],
       [-1.00949995e+00],
       [ 4.12353351e-01]])

In [15]:
#Calculate the beta RLS
beta_rls = beta_ols - np.linalg.inv(X.T @ X)  @ L.T @ np.linalg.inv(L @ np.linalg.inv(X.T @ X) @ L.T) @ (L@ beta_ols - r)
beta_rls

array([[-4.03563641e+00],
       [-7.55931949e+02],
       [ 3.02509877e+03],
       [ 4.64319418e-02],
       [ 3.69444500e-02],
       [-8.33763919e-02],
       [-2.91634922e-01],
       [ 4.37698821e-01],
       [ 8.53936101e-01],
       [ 2.38031816e-13],
       [-2.80331314e-14],
       [ 3.56048524e-13],
       [ 6.77236045e-14],
       [ 2.95541369e-13],
       [-7.92699240e-14]])

2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

$$
Var\left( \widehat{\beta }^{\left( RLS\right) }\right) =\sigma ^{2}\left[
X^{T}X\right] ^{-1}-\sigma ^{2}\left[ X^{T}X\right] ^{-1}L^{T}\left( L\left(
X^{T}X\right) ^{-1}L^{T}\right) ^{-1}L\left( X^{T}X\right) ^{-1}
$$

In [17]:
#We calculate the Y_pred
y_pred = X @ beta_ols

# We calculate the standard error of the regression
sigma2 = ( (1 / (len(greene) - X.shape[1]+1-L.shape[0])) * (y_pred - lnCT).T  @ (y_pred - lnCT))
sigma = np.sqrt(sigma2)
sigma

array([[0.67686133]])

In [18]:
#
Cov_Var_RLS=sigma*(np.linalg.inv(X.T@X))-sigma*(np.linalg.inv(X.T@X)@L.T@np.linalg.inv(L@np.linalg.inv(X.T@X)@L.T)@L@np.linalg.inv(X.T@X))
Cov_Var_RLS

array([[ 3.66525648e+01, -4.39021577e+00,  2.28123929e-01,
         8.13030672e-01, -6.37285521e-01, -1.75745151e-01,
        -6.89063401e+00,  5.34277153e+00,  1.54786251e+00,
        -1.43324996e-09,  6.68620714e-11, -5.83554538e-10,
        -3.97264444e-10, -1.46235379e-09,  9.14806009e-11],
       [-5.02893493e+00,  3.72108449e+11, -1.48843380e+12,
        -1.02175133e-01,  7.75979700e-02,  2.45771628e-02,
         9.04776338e-01, -7.44731188e-01, -1.60045148e-01,
        -8.44408987e-11,  3.25628413e-12, -1.81774595e-11,
        -1.46229695e-11, -8.56203997e-11,  4.18864943e-12],
       [ 2.78158067e+00, -1.48843380e+12,  5.95373519e+12,
         1.26553127e-03,  7.39562452e-03, -8.66115580e-03,
        -3.63969880e-01,  4.36703808e-01, -7.27339361e-02,
         4.36727987e-10, -1.72555303e-11,  9.85309612e-11,
         1.27897692e-10,  4.10977918e-10, -1.27045041e-11],
       [ 8.13030672e-01, -1.02989950e-01,  4.52479989e-03,
         1.94926814e-02, -1.30314003e-02, -6.46128118e-03,
        -1.55687752e-01,  1.04931961e-01,  5.07557909e-02,
        -1.87905247e-14, -1.81174520e-14, -4.46448434e-14,
        -1.38236644e-13, -2.62567745e-14, -1.18051402e-13],
       [-6.37285521e-01,  8.11975538e-02, -7.00271094e-03,
        -1.30314003e-02,  2.21670268e-02, -9.13562653e-03,
         1.05395334e-01, -1.74851695e-01,  6.94563609e-02,
        -2.90670266e-14, -2.91780489e-15, -2.15036322e-14,
        -3.25121874e-14, -3.36293493e-14, -2.52714516e-14],
       [-1.75745151e-01,  2.17923961e-02,  2.47791105e-03,
        -6.46128118e-03, -9.13562653e-03,  1.55969077e-02,
         5.02924181e-02,  6.99197337e-02, -1.20212152e-01,
        -2.60099234e-13, -4.26991342e-15, -1.26728489e-13,
        -1.37707554e-13, -3.00343084e-13, -7.23310301e-14],
       [-6.89063401e+00,  8.23380666e-01, -3.83871902e-02,
        -1.55687752e-01,  1.05395334e-01,  5.02924181e-02,
         1.31986423e+00, -8.88914912e-01, -4.30949323e-01,
         2.35615971e-10, -1.61248792e-11,  8.38618064e-11,
         5.48148194e-11,  2.47268872e-10, -4.44533299e-11],
       [ 5.34277153e+00, -6.50026851e-01,  5.78864599e-02,
         1.04931961e-01, -1.74851695e-01,  6.99197337e-02,
        -8.88914912e-01,  1.44232496e+00, -5.53410047e-01,
         5.51025892e-12, -1.07647224e-12,  3.31268346e-12,
         7.03437308e-13,  5.73052716e-12, -4.56168436e-12],
       [ 1.54786250e+00, -1.73353814e-01, -1.94992731e-02,
         5.07557909e-02,  6.94563609e-02, -1.20212152e-01,
        -4.30949322e-01, -5.53410047e-01,  9.84359369e-01,
        -3.09512416e-11, -4.04987155e-12, -3.58966190e-11,
        -1.25650601e-11, -5.65734126e-11, -2.61239919e-11],
       [-1.47474566e-09, -8.25508550e-11,  3.25201199e-10,
         1.13214993e-13, -1.74582571e-14,  7.19771465e-14,
         2.55340638e-10,  2.20286012e-11,  1.39912970e-10,
        -2.17887930e-11,  1.04288800e-12, -9.08539910e-12,
        -6.25766106e-12, -2.34550157e-11,  1.40376599e-12],
       [ 1.74260606e-11,  1.58717484e-12, -6.17284002e-12,
        -4.11302936e-15,  7.45931095e-17, -1.82276069e-15,
        -3.28093108e-12, -1.03028697e-13, -1.26121336e-12,
         3.04922754e-13, -6.21724894e-15,  2.30371278e-14,
         1.86795024e-14,  2.54740673e-13,  1.73194792e-14],
       [-7.99047939e-10, -5.88489257e-11,  2.32311947e-10,
         6.20215684e-14, -3.52461116e-14,  7.74779546e-14,
         1.44208201e-10,  1.39599443e-12,  7.18713977e-11,
        -1.25124355e-11,  8.72746320e-13, -3.98170386e-12,
        -2.16227036e-12, -1.34825484e-11,  2.72937228e-12],
       [-1.72242665e-10, -8.39861514e-12,  3.28554961e-11,
         1.59733338e-14,  3.46944695e-17,  8.64759653e-15,
         3.06048520e-11,  3.94351218e-12,  1.35784717e-11,
        -2.65698574e-12,  8.13238366e-14, -5.24691401e-13,
        -8.89954777e-13, -2.51754173e-12, -8.61533067e-14],
       [-4.24620339e-10, -3.63229447e-11,  1.43131729e-10,
         2.95596880e-14, -6.25107605e-14,  1.07427955e-13,
         8.13713541e-11, -1.07949205e-11,  3.77013976e-11,
        -7.04503123e-12,  1.25216504e-12, -2.89102076e-12,
        -8.92619312e-13, -7.89768251e-12,  5.24957855e-12],
       [-2.42784459e-10, -1.83675297e-11,  7.34559080e-11,
         2.85188539e-15, -6.88338275e-15, -3.60822483e-16,
         4.20783408e-11,  1.04805054e-12,  2.46576093e-11,
        -3.60933505e-12,  1.60538249e-13, -1.58251190e-12,
        -4.92050845e-13, -4.16178203e-12,  3.41060513e-13]])

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

In [4]:
# read REC0111 data
#!pip install savReaderWriter
# install pyreadstat
#!pip install pyreadstat

Requirement already satisfied: savReaderWriter in c:\users\valer\anaconda3\lib\site-packages (3.4.2)
Requirement already satisfied: pyreadstat in c:\users\valer\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: pandas>=1.2.0 in c:\users\valer\anaconda3\lib\site-packages (from pyreadstat) (1.4.4)
Requirement already satisfied: numpy>=1.18.5 in c:\users\valer\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\valer\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\valer\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\valer\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)

In [5]:
import pandas as pd ## Import pandas library 
import numpy as np ## Import numpy library

In [6]:
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [7]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primario - conglomerado',
 'V023': 'Dominio de ejemplo - Departamento',
 'V024': 'Región',
 'V025': 'Tipo de lugar de residencia',
 'V026': 'El lugar de residencia en el que se entrevistó - De Facto',
 'V027': 'Número de visitas',
 'V028': 'Identificación del entrevistador',
 'V029': 'Identificador del digitador',
 'V030': 'Supervisor de campo',
 'V031': 'Editor de campo',
 'V032': 'Editor de la oficina',
 'V033': 'Selección final del área de probabilidad',
 'V034': 'Número de orden del esposo',
 'V040': 'Altitud del conglomerado en metros',
 'V042': 'Selección de hogar para hemoglobina',
 'V043': 'Selección para módulo de estatus de mujeres',
 'V044': 'Selección para módulo de violencia domestica',
 'V000': 'Código y fase del país',
 'Q105DD': 'Dia de nacimeinto de la entrevistada',
 'V101': 'Región',
 'V102': 'Tipo de lugar de residencia',
 'V103': 'Lugar de residencia de la infancia',
 'V104': 'Cuanto tiempo tiene viviendo continuamente en el lugar de residencia actual',
 'V105': 'Tipo de lugar de residencia anteriormente',
 'V106': 'Nivel educativo más alto',
 'V107': 'Año/grado de educación más alto aprobado',
 'V113': 'Fuente principal de abasteciemiento de agua potable que utilizan en su hogar para tomar o beber',
 'V115': 'Tiempo para llegar a la fuente de agua',
 'V116': 'Tipo de instalación sanitaria',
 'V119': 'En su hogar tiene: electricidad',
 'V120': 'En su hogar tiene: radio',
 'V121': 'En su hogar tiene: televisión',
 'V122': 'En su hogar tiene: refrigerador',
 'V123': 'En su hogar tiene: bicicleta',
 'V124': 'En su hogar tiene: motocicleta/motocar',
 'V125': 'En su hogar tiene: coche/camión',
 'V127': 'Material predominante del piso de la vivienda',
 'V128': 'Material predominante de las paredes exteriores de la vivienda',
 'V129': 'Material predominante del techo de la vivienda',
 'V130': 'Religión',
 'V131': 'Etnicidad',
 'V133': 'Educación en años simples',
 'V134': 'El lugar en el que se realizó la entrevista  De-facto',
 'V135': 'Residente habitual o visitante',
 'V136': 'Número de miembros del hogar',
 'V137': 'Número de niños de 6 años de edad ',
 'V138': 'Número de mujeres de 15 a 49 años de edad elegibles en el hogar ',
 'V139': 'Región, residencia habitual De-jure',
 'V140': 'Tipo de área de residencia De-jure',
 'V141': 'Lugar de residencia De-jure',
 'V149': 'Logro educativo',
 'V150': 'Relación con el jefe del hogar',
 'V151': 'Sexo del Jefe del Hogar',
 'V152': 'Edad del jefe del hogar',
 'V153': 'En su hogar tiene: teléfono',
 'AWFACTT': 'Factor todas las mujeres - total',
 'AWFACTU': 'Factor todas las mujeres - urbano/rural',
 'AWFACTR': 'Factor todas las mujeres - regional',
 'AWFACTE': 'Factor todas las mujeres - educación',
 'AWFACTW': 'Factor todas las mujeres - índice de riqueza',
 'V155': 'Alfabetización',
 'V156': 'Alguna vez participó en un programa de alfabetización (no incluyendo la escuela primaria)',
 'V157': 'Frecuencia de lectura de un periódico o revista',
 'V158': 'Frecuencia de escuchar radio',
 'V159': 'Frecuencia de ver televisión',
 'V160': 'Baño compartido con otros hogares',
 'V161': 'Tipo de combustible para cocinar',
 'V166': 'Resultados de la prueba del yodo en la sal',
 'V167': 'Número de viajes en los últimos 12 meses',
 'V168': 'Afuera más de un mes en los últimos 12 meses',
 'ML101': 'Tipo de mosquitero que utilizo para dormir última noche',
 'QD333_1': 'Alguna dificultad o limitación permanente para ver, aún usando anteojos',
 'QD333_2': 'Alguna dificultad o limitación permanente para oir, aún usando audífonos',
 'QD333_3': 'Alguna dificultad o limitación permanente para hablar o comunicarse, aún usando la lengua de señas u otro',
 'QD333_4': 'Alguna dificultad o limitación permanente para moverse o caminar para usar brazos y/o piernas',
 'QD333_5': 'Alguna dificultad o limitación permanente para entender o aprender (concentrarse y recordarse)',
 'QD333_6': 'Alguna dificultad o limitación permanente para relacionarse con los demás, por sus pensamientos, sentimientos, emociones o conductas',
 'UBIGEO': 'Código de Ubicación Gegráfica',
 'V022': 'Estratos',
 'V005': 'Factor de ponderacion',
 'V190': 'Índice de riqueza',
 'V191': 'Factor de puntuación del índice de riqueza (5 decimales)',
 'mujeres12a49': 'Mujeres de 12 a 49 años de edad',
 'NCONGLOME': 'Número de Conglomerado (proveniente del marco)'}

1. Check if CASEID identifies each observation uniquely. Hint: Use is_unique method.

In [8]:
rec1['CASEID'].is_unique ## TRUE, each ID is unique

True

2. Make the CASEID column the index of your data set. Hint: Use set_index.

In [9]:
rec1.columns ## Show columns names from base rec1

Index(['ID1', 'HHID', 'CASEID', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008',
       'V009',
       ...
       'QD333_4', 'QD333_5', 'QD333_6', 'UBIGEO', 'V022', 'V005', 'V190',
       'V191', 'mujeres12a49', 'NCONGLOME'],
      dtype='object', length=105)

In [10]:
rec1.set_index('CASEID', drop=True, inplace=True) ## use set_index on data rec1 to convert CASEID to the index of the data
rec1

,ID1,HHID,V001,V002,V003,V004,V007,V008,V009,V010,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
CASEID,,,,,,,,,,,,,,,,,,,,,
000100201 2,2019.0,000100201,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,No,No,No,010101,3.0,154803.0,Rico,1.234450,Mujeres de 15 a 49 años de edad,7065.0
000100201 3,2019.0,000100201,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,No,No,No,010101,3.0,154803.0,Rico,1.234450,"Mujeres de 12 a 14 de edad, nunca embarazadas",7065.0
000102801 2,2019.0,000102801,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,No,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0
000102801 6,2019.0,000102801,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,No,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0
000104801 2,2019.0,000104801,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,No,No,No,010101,3.0,154803.0,Pobrer,-0.256431,Mujeres de 15 a 49 años de edad,7065.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325406201 2,2019.0,325406201,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.750187,Mujeres de 15 a 49 años de edad,15783.0
325406301 2,2019.0,325406301,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.676861,Mujeres de 15 a 49 años de edad,15783.0
325407001 2,2019.0,325407001,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,No,No,No,250401,249.0,459792.0,El más pobre,-1.585333,Mujeres de 15 a 49 años de edad,15783.0
325407201 2,2019.0,325407201,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,No,No,No,250401,249.0,459792.0,El más pobre,-1.650159,Mujeres de 15 a 49 años de edad,15783.0
325407401 2,2019.0,325407401,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.644720,Mujeres de 15 a 49 años de edad,15783.0

3. Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.

In [11]:
rec1.V010 ## indicates values of  V010 'Año de nacimiento de la entrevistada'

CASEID
      000100201  2    1986.0
      000100201  3    2007.0
      000102801  2    1983.0
      000102801  6    1970.0
      000104801  2    1991.0
                       ...
      325406201  2    1971.0
      325406301  2    1988.0
      325407001  2    1973.0
      325407201  2    1994.0
      325407401  2    1996.0
Name: V010, Length: 38335, dtype: float64

In [12]:
#first step --> Urban areas
rec1 = rec1[rec1['V102'] == 'Urbano'] ## filter observations of Urban areas

In [13]:
#second step -->  women who are 15-30 years old
rec1['V010'].min() ## shows the minimun value of V010

1969.0

In [14]:
rec1['V010'].max() ## shows the maximum value of V010

2007.0

In [15]:
rec1.shape ## verifica tamaño base de datos filte

(26133, 104)

In [16]:
2019-15 ## from the year of the survey, subtract  15 years

2004

In [17]:
2019-30 ## from the year of the survey, subtract  30 years

1989

In [18]:
rec1 = rec1.query('  V010  >= 1989  &  V010  <= 2004') ## filter observations of women who are 15-30 years old based on years of her birth

In [19]:
rec1.shape ## check new database size

(12127, 104)

In [20]:
rec1['V010'].min() ## check new minimun value of V010

1989.0

In [21]:
rec1['V010'].max()  ## check new maximum value of V010

2004.0

4. Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.

In [22]:
rec1.V009 ## ## indicates values of  V009 'Mes de nacimiento de la entrevistada'

CASEID
      000104801  2     5.0
      000116701  1     6.0
      000119101  1     9.0
      000203001  2     5.0
      000204001  3     9.0
                      ...
      324202401  2     2.0
      324202501  3     5.0
      324203901  1     8.0
      324204501  2     5.0
      324206901  3    10.0
Name: V009, Length: 12127, dtype: float64

In [23]:
def conditions(x):  ## Function that names months based on month number
    if   x == 1 :   return "jan" 
    elif x == 2 :   return "feb"
    elif x == 3 :   return "mar"
    elif x == 4 :   return "apr"
    elif x == 5 :   return "may"
    elif x == 6 :   return "jun"
    elif x == 7 :   return "jul"
    elif x == 8 :   return "aug"
    elif x == 9 :   return "sep"
    elif x == 10 :   return "oct"
    elif x == 11 :   return "nov"
    else:   return "dec"

In [24]:
func         = np.vectorize(conditions) ## vectorizes the results of the conditions function
rec1['month'] = func(rec1['V009']) ## applies the function to the variable V009 and creates the new column 'month'

In [25]:
rec1.month ## display the new column in the same base rec1

CASEID
      000104801  2    may
      000116701  1    jun
      000119101  1    sep
      000203001  2    may
      000204001  3    sep
                     ...
      324202401  2    feb
      324202501  3    may
      324203901  1    aug
      324204501  2    may
      324206901  3    oct
Name: month, Length: 12127, dtype: object